# -*- coding: utf-8 -*-
"""剩余 i18n 补漏键表（由 gen_i18n.py 调用 register(k)）。"""


def register(k):
    # ---------- 首页 ----------
    k("Home_ToggleSysProxy", "系统代理", "System proxy", "系統代理", "システムプロキシ", "시스템 프록시", "Systemproxy", "Proxy del sistema", "Системный прокси", "Sistem proxy", "Proxy sistem", "پروکسی سیستم", "بروكسي النظام", "Систем прокси")
    k("Home_ToggleTun", "TUN 模式", "TUN mode", "TUN 模式", "TUNモード", "TUN 모드", "TUN-Modus", "Modo TUN", "Режим TUN", "TUN modu", "Mode TUN", "حالت TUN", "وضع TUN", "TUN режимы")
    k("Home_MixedPortLabel", "混合端口: ", "Mixed port: ", "混合連接埠: ", "混合ポート: ", "혼합 포트: ", "Mixed-Port: ", "Puerto mixto: ", "Смешанный порт: ", "Karma port: ", "Port campuran: ", "پورت ترکیبی: ", "المنفذ المختلط: ", "Кушылган порт: ")
    k("Home_UptimeLabel", "运行时间: ", "Uptime: ", "執行時間: ", "稼働時間: ", "가동 시간: ", "Laufzeit: ", "Tiempo activo: ", "Время работы: ", "Çalışma süresi: ", "Waktu berjalan: ", "زمان اجرا: ", "وقت التشغيل: ", "Эш вакыты: ")
    k("Home_RulesCountLabel", "规则数量: ", "Rules: ", "規則數量: ", "ルール数: ", "규칙 수: ", "Regeln: ", "Reglas: ", "Правил: ", "Kural sayısı: ", "Jumlah aturan: ", "تعداد قوانین: ", "عدد القواعد: ", "Кагыйдә саны: ")
    k("Home_RestartCore", "重启内核", "Restart core", "重啟核心", "コア再起動", "코어 재시작", "Kern neu starten", "Reiniciar núcleo", "Перезапустить ядро", "Çekirdeği yeniden başlat", "Restart core", "ری‌استارت هسته", "إعادة تشغيل النواة", "Йөзәкне яңадан башлау")
    k("Home_OpenLogs", "打开日志目录", "Open log folder", "開啟日誌目錄", "ログフォルダを開く", "로그 폴더 열기", "Log-Ordner öffnen", "Abrir carpeta de logs", "Открыть папку логов", "Kayıt klasörünü aç", "Buka folder log", "باز کردن پوشه گزارش‌ها", "افتح مجلد السجلات", "Журнал папкасын ачу")

    # ---------- 订阅卡片 ----------
    k("Profiles_CurrentBadge", "当前", "Current", "目前", "現在", "현재", "Aktuell", "Actual", "Текущая", "Mevcut", "Saat ini", "فعلی", "الحالي", "Хәзерге")
    k("Profiles_TipUpdate", "更新订阅", "Update profile", "更新訂閱", "購読を更新", "구독 업데이트", "Profil aktualisieren", "Actualizar perfil", "Обновить подписку", "Profili güncelle", "Perbarui profil", "به‌روزرسانی اشتراک", "تحديث الملف", "Профильне яңарту")
    k("Profiles_TipDelete", "删除订阅", "Delete profile", "刪除訂閱", "購読を削除", "구독 삭제", "Profil löschen", "Eliminar perfil", "Удалить подписку", "Profili sil", "Hapus profil", "حذف اشتراک", "حذف الملف", "Профильне бетерү")
    k("Proxies_TipGroupTest", "整组测速", "Test group latency", "整組測速", "グループ遅延テスト", "그룹 지연 테스트", "Gruppen-Latenztest", "Probar latencia del grupo", "Тест задержки группы", "Grup gecikme testi", "Uji latensi grup", "تست تأخیر گروه", "اختبار زمن المجموعة", "Төркем тоткарлыгы тикшерү")

    # ---------- 编辑订阅对话框 ----------
    k("ProfileEdit_NamePlaceholder", "订阅名称", "Profile name", "訂閱名稱", "購読名", "구독 이름", "Profilname", "Nombre del perfil", "Имя подписки", "Profil adı", "Nama profil", "نام پروفایل", "اسم الملف", "Профиль исеме")
    k("ProfileEdit_DescPlaceholder", "描述（可选）", "Description (optional)", "描述（可選）", "説明（任意）", "설명(선택)", "Beschreibung (optional)", "Descripción (opcional)", "Описание (необяз.)", "설명(선택)", "Deskripsi (opsional)", "توضیحات (اختیاری)", "وصف (اختياري)", "Тасвирлама (теләсә)")
    k("ProfileEdit_UaPlaceholder", "默认 clash-verge/v2.5.2", "Default clash-verge/v2.5.2", "預設 clash-verge/v2.5.2", "既定 clash-verge/v2.5.2", "기본 clash-verge/v2.5.2", "Standard clash-verge/v2.5.2", "Predeterminado clash-verge/v2.5.2", "По умолчанию clash-verge/v2.5.2", "Varsayılan clash-verge/v2.5.2", "Bawaan clash-verge/v2.5.2", "پیش‌فرض clash-verge/v2.5.2", "افتراضي clash-verge/v2.5.2", "Кабул clash-verge/v2.5.2")
    k("ProfileEdit_InvalidCertLabel", "接受无效 TLS 证书（危险）", "Accept invalid TLS certificates (dangerous)", "接受無效 TLS 憑證（危險）", "無効なTLS証明書を許可（危険）", "잘못된 TLS 인증서 허용(위험)", "Ungültige TLS-Zertifikate akzeptieren (gefährlich)", "Aceptar certificados TLS no válidos (peligroso)", "Принимать недействительные TLS-сертификаты (опасно)", "Geçersiz TLS sertifikalarını kabul et (tehlikeli)", "Terima sertifikat TLS tidak valid (berbahaya)", "پذیرش گواهی TLS نامعتبر (خطرناک)", "قبول شهادات TLS غير صالحة (خطر)", "Хата TLS сертификатларын кабул итү (хәтәр)")
    k("ProfileEdit_AutoUpdateLabel", "参与自动更新", "Include in auto update", "參與自動更新", "自動更新に含める", "자동 업데이트 포함", "An Auto-Update teilnehmen", "Incluir en actualización automática", "Участвовать в автообновлении", "Otomatik güncellemeye dahil et", "Sertakan pembaruan otomatis", "در به‌روزرسانی خودکار شرکت کن", "المشاركة في التحديث التلقائي", "Автояңартуда катнаш")
    k("ProfileEdit_ChannelAuto", "自动回退（直连→内核→系统）", "Auto fallback (direct → core → system)", "自動回退（直連→核心→系統）", "自動フォールバック（直接→コア→システム）", "자동 폴백(다이렉트→코어→시스템)", "Automatisch (Direkt→Kern→System)", "Retroceso automático (directo→núcleo→sistema)", "Авто-откат (напрямую→ядро→система)", "Otomatik (doğrudan→çekirdek→sistem)", "Fallback otomatis (langsung→core→sistem)", "پشتیبان‌گیری خودکار (مستقیم→هسته→سیستم)", "تراجع تلقائي (مباشر→نواة→نظام)", "Авто (туры→йөзәк→система)")
    k("ProfileEdit_ChannelCore", "经内核代理", "Via core proxy", "經核心代理", "コアプロキシ経由", "코어 프록시 경유", "Über Kern-Proxy", "Vía proxy del núcleo", "Через прокси ядра", "Çekirdek proxy üzerinden", "Via proxy core", "از طریق پروکسی هسته", "عبر بروكسي النواة", "Йөзәк прокси аша")
    k("ProfileEdit_ChannelSystem", "经系统代理", "Via system proxy", "經系統代理", "システムプロキシ経由", "시스템 프록시 경유", "Über Systemproxy", "Vía proxy del sistema", "Через системный прокси", "Sistem proxy üzerinden", "Via proxy sistem", "از طریق پروکسی سیستم", "عبر بروكسي النظام", "Систем прокси аша")
    k("ProfileEdit_FieldName", "名称", "Name", "名稱", "名前", "이름", "Name", "Nombre", "Имя", "Ad", "Nama", "نام", "الاسم", "Исем")
    k("ProfileEdit_FieldDesc", "描述", "Description", "描述", "説明", "설명", "Beschreibung", "Descripción", "Описание", "Açıklama", "Deskripsi", "توضیحات", "الوصف", "Тасвирлама")
    k("ProfileEdit_FieldUrl", "订阅 URL", "Subscription URL", "訂閱 URL", "購読URL", "구독 URL", "Abo-URL", "URL de suscripción", "URL подписки", "Abonelik URL", "URL langganan", "آدرس اشتراک", "رابط الاشتراك", "Абу URL")
    k("ProfileEdit_FieldChannel", "更新通道", "Update channel", "更新通道", "更新チャネル", "업데이트 채널", "Update-Kanal", "Canal de actualización", "Канал обновления", "Güncelleme kanalı", "Saluran pembaruan", "کانال به‌روزرسانی", "قناة التحديث", "Яңарту каналы")
    k("ProfileEdit_FieldInterval", "更新间隔（分钟，0=不自动）", "Update interval (minutes, 0 = off)", "更新間隔（分鐘，0=不自動）", "更新間隔（分、0=手動）", "업데이트 간격(분, 0=끄기)", "Intervall (Minuten, 0 = aus)", "Intervalo (minutos, 0 = manual)", "Интервал (мин, 0 = выкл.)", "Aralık (dakika, 0 = kapalı)", "Interval (menit, 0 = mati)", "بازه (دقیقه، 0=خاموش)", "الفاصل الزمني (دقائق، 0=إيقاف)", "Интервал (мин, 0=сүнек)")
    k("ProfileEdit_FieldTimeout", "下载超时（秒）", "Download timeout (seconds)", "下載逾時（秒）", "DLタイムアウト（秒）", "다운로드 시간 초과(초)", "Download-Timeout (Sek.)", "Tiempo de espera (segundos)", "Таймаут загрузки (сек)", "İndirme zaman aşımı (sn)", "Batas waktu unduh (detik)", "زمان مهلت دانلود (ثانیه)", "مهلة التنزيل (ثوانٍ)", "Йөкләү таймауты (сек)")
    k("ProfileEdit_FieldUa", "User-Agent", "User-Agent", "User-Agent", "User-Agent", "사용자 에이전트", "User-Agent", "User-Agent", "User-Agent", "User-Agent", "User-Agent", "User-Agent", "User-Agent", "User-Agent")

    # ---------- 增强编辑 ----------
    k("Enhace_SaveAndApply", "保存并应用", "Save & apply", "儲存並應用", "保存して適用", "저장 후 적용", "Speichern & anwenden", "Guardar y aplicar", "Сохранить и применить", "Kaydet ve uygula", "Simpan & terapkan", "ذخیره و اعمال", "حفظ وتطبيق", "Саклау һәм куллану")
    k("Enhance_NameGlobalMerge", "全局 Merge", "Global Merge", "全域 Merge", "グローバル Merge", "글로벌 Merge", "Globales Merge", "Merge global", "Глобальный Merge", "Küresel Merge", "Merge global", "Merge سراسری", "Merge عام", "Глобаль Merge")
    k("Enhance_NameGlobalScript", "全局 Script", "Global Script", "全域 Script", "グローバル Script", "글로벌 Script", "Globales Script", "Script global", "Глобальный Script", "Küresel Script", "Script global", "Script سراسری", "Script عام", "Глобаль Script")
    k("Enhance_NameProfileMerge", "订阅 Merge", "Profile Merge", "訂閱 Merge", "購読 Merge", "구독 Merge", "Profil-Merge", "Merge de perfil", "Merge профиля", "Profil Merge", "Merge profil", "Merge اشتراک", "Merge للملف", "Профиль Merge")
    k("Enhance_NameProfileScript", "订阅 Script", "Profile Script", "訂閱 Script", "購読 Script", "구독 Script", "Profil-Script", "Script de perfil", "Script профиля", "Profil Script", "Script profil", "Script اشتراک", "Script للملف", "Профиль Script")
    k("Enhance_NameProfileRules", "订阅 Rules", "Profile Rules", "訂閱 Rules", "購読 Rules", "구독 Rules", "Profil-Regeln", "Rules de perfil", "Правила профиля", "Profil kuralları", "Aturan profil", "قوانین اشتراک", "قواعد الملف", "Профиль кагыйдәләре")
    k("Enhance_NameProfileProxies", "订阅 Proxies", "Profile Proxies", "訂閱 Proxies", "購読 Proxies", "구독 Proxies", "Profil-Proxys", "Proxies de perfil", "Прокси профиля", "Profil proxy'leri", "Proxy profil", "پروکسی اشتراک", "بروكسي الملف", "Профиль проксилары")
    k("Enhance_NameProfileGroups", "订阅 Groups", "Profile Groups", "訂閱 Groups", "購読 Groups", "구독 Groups", "Profil-Gruppen", "Groups de perfil", "Группы профиля", "Profil grupları", "Grup profil", "گروه‌های اشتراک", "مجموعات الملف", "Профиль төркемнәре")
    k("Enhance_TypedName", "{0} 增强", "{0} enhancement", "{0} 增強", "{0} 拡張", "{0} 향상", "{0}-Erweiterung", "Mejora de {0}", "Улучшение {0}", "{0} geliştirme", "Peningkatan {0}", "بهبود {0}", "تحسين {0}", "{0} яхшырту")
    k("Enhance_ScriptNeedsMain", "Script 文件必须定义 main(config, profileName) 函数", "Script must define main(config, profileName)", "Script 檔案必須定義 main(config, profileName) 函式", "Scriptにはmain(config, profileName)が必要です", "Script에는 main(config, profileName)이 필요합니다", "Script muss main(config, profileName) definieren", "El script debe definir main(config, profileName)", "Скрипт должен определять main(config, profileName)", "Script, main(config, profileName) tanımlamalı", "Script harus mendefinisikan main(config, profileName)", "اسکریپت باید main(config, profileName) را تعریف کند", "يجب أن يعرّف السكربت main(config, profileName)", "Script main(config, profileName) булырга тиеш")

    # ---------- 校验 / 工具 ----------
    k("Validator_InvalidYamlMapping", "内容不是有效的 YAML 映射", "Content is not a valid YAML mapping", "內容不是有效的 YAML 映射", "有効なYAMLマッピングではありません", "유효한 YAML 매핑이 아닙니다", "Inhalt ist kein gültiges YAML-Mapping", "El contenido no es un mapeo YAML válido", "Содержимое не является корректным YAML-отображением", "İçerik geçerli bir YAML eşlemesi değil", "Konten bukan pemetaan YAML valid", "محتوا نگاشت YAML معتبر نیست", "المحتوى ليس تعيين YAML صالحًا", "Эчәлек дөрес YAML булмый")
    k("Validator_InvalidYaml", "内容不是有效的 YAML", "Content is not valid YAML", "內容不是有效的 YAML", "有効なYAMLではありません", "유효한 YAML이 아닙니다", "Inhalt ist kein gültiges YAML", "El contenido no es YAML válido", "Содержимое не является корректным YAML", "İçerik geçerli YAML değil", "Konten bukan YAML valid", "محتوا YAML معتبر نیست", "المحتوى ليس YAML صالحًا", "Эчәлек дөрес YAML түгел")
    k("Validator_NotClash", "配置中缺少 proxies / proxy-providers，不是有效的 Clash 配置", "Missing proxies / proxy-providers; not a valid Clash config", "設定缺少 proxies / proxy-providers，不是有效的 Clash 設定", "proxies/proxy-providersがありません", "proxies/proxy-providers가 없습니다", "proxies/proxy-providers fehlen", "Faltan proxies/proxy-providers", "Отсутствуют proxies/proxy-providers", "proxies/proxy-providers eksik", "proxies/proxy-providers tidak ada", "proxies/proxy-providers وجود ندارد", "تفتقد proxies/proxy-providers", "proxies/proxy-providers җитми")
    k("Enhance_GlobalNotSupported", "该类型不支持全局增强", "This type has no global enhancement", "該類型不支援全域增強", "この種類はグローバル拡張非対応", "이 유형은 글로벌 향상 미지원", "Keine globale Erweiterung für diesen Typ", "Este tipo no admite mejora global", "Глобальное улучшение для этого типа недоступно", "Bu tür küresel geliştirmeyi desteklemiyor", "Tipe ini tidak mendukung peningkatan global", "این نوع از بهبود سراسری پشتیبانی نمی‌کند", "هذا النوع لا يدعم التحسين العام", "Бу төр глобаль яхшыртуну хупламый")
    k("Yaml_ParseFailed", "YAML 解析失败: {0}", "YAML parse failed: {0}", "YAML 解析失敗: {0}", "YAML解析に失敗: {0}", "YAML 구문 분석 실패: {0}", "YAML-Parsing fehlgeschlagen: {0}", "Error al analizar YAML: {0}", "Ошибка разбора YAML: {0}", "YAML ayrıştırma başarısız: {0}", "Gagal mengurai YAML: {0}", "تجزیه YAML ناموفق: {0}", "فشل تحليل YAML: {0}", "YAML тезү хата: {0}")
    k("Format_Timeout", "超时", "Timeout", "逾時", "タイムアウト", "시간 초과", "Timeout", "Tiempo agotado", "Таймаут", "Zaman aşımı", "Waktu habis", "پایان زمان", "انتهاء المهلة", "Вакыт чыгарды")
    k("Paths_CoreMissing", "未找到内置 mihomo 内核（core\\mihomo.exe）", "Bundled mihomo core not found (core\\mihomo.exe)", "未找到內建 mihomo 核心（core\\mihomo.exe）", "内蔵mihomoコアが見つかりません", "내장 mihomo 코어를 찾을 수 없습니다", "Mihomo-Kern nicht gefunden (core\\mihomo.exe)", "No se encontró el núcleo mihomo", "Встроенное ядро mihomo не найдено", "Yerleşik mihomo çekirdeği bulunamadı", "Core mihomo bawaan tidak ditemukan", "هسته داخلی mihomo یافت نشد", "لم يُعثر على نواة mihomo المدمجة", "Эчке mihomo йөзәге табылмады")

    # ---------- 代理页 VM / 规则页 VM ----------
    k("Proxies_CurrentNow", "当前: {0}", "Now: {0}", "目前: {0}", "現在: {0}", "현재: {0}", "Aktuell: {0}", "Actual: {0}", "Сейчас: {0}", "Şu an: {0}", "Saat ini: {0}", "الان: {0}", "الآن: {0}", "Хәзер: {0}")
    k("Proxies_NodeCount", "{0} 个", "{0} nodes", "{0} 個", "{0} 件", "{0}개", "{0} Knoten", "{0} nodos", "{0} узлов", "{0} düğüm", "{0} node", "{0} گره", "{0} عقدة", "{0} төен")
    k("ProxiesVM_ModeSwitchFailed", "模式切换失败: {0}", "Mode switch failed: {0}", "模式切換失敗: {0}", "モード切替に失敗: {0}", "모드 전환 실패: {0}", "Moduswechsel fehlgeschlagen: {0}", "Error al cambiar de modo: {0}", "Ошибка смены режима: {0}", "Mod değiştirme başarısız: {0}", "Gagal mengganti mode: {0}", "تغییر حالت ناموفق: {0}", "فشل تغيير الوضع: {0}", "Режим алмаштыру хата: {0}")
    k("ProxiesVM_ClosedOldConnections", "切换节点后已关闭 {0} 个旧连接", "Closed {0} old connections after switching", "切換節點後已關閉 {0} 個舊連接", "切替後に{0}件の接続を閉じました", "전환 후 {0}개 연결 닫음", "{0} alte Verbindungen geschlossen", "{0} conexiones antiguas cerradas", "После переключения закрыто {0} соединений", "Geçiş sonrası {0} bağlantı kapatıldı", "{0} koneksi lama ditutup", "پس از تغییر {0} اتصال بسته شد", "أُغلق {0} اتصالًا قديمًا", "Алмашкач {0} тоташу ябылды")
    k("ProxiesVM_NodeSwitchFailed", "切换节点失败 [{0} → {1}]: {2}", "Node switch failed [{0} → {1}]: {2}", "切換節點失敗 [{0} → {1}]: {2}", "ノード切替失敗 [{0} → {1}]: {2}", "노드 전환 실패 [{0} → {1}]: {2}", "Knotenwechsel fehlgeschlagen [{0} → {1}]: {2}", "Error al cambiar nodo [{0} → {1}]: {2}", "Ошибка смены узла [{0} → {1}]: {2}", "Düğüm geçişi başarısız [{0} → {1}]: {2}", "Gagal beralih node [{0} → {1}]: {2}", "تغییر گره ناموفق [{0} → {1}]: {2}", "فشل تبديل العقدة [{0} → {1}]: {2}", "Төен алмаштыру хата [{0} → {1}]: {2}")
    k("RulesVM_LoadFailed", "加载失败: {0}", "Load failed: {0}", "載入失敗: {0}", "読み込み失敗: {0}", "로드 실패: {0}", "Laden fehlgeschlagen: {0}", "Error al cargar: {0}", "Ошибка загрузки: {0}", "Yükleme başarısız: {0}", "Gagal memuat: {0}", "بارگذاری ناموفق: {0}", "فشل التحميل: {0}", "Йөкләү хата: {0}")
    k("RulesVM_Count", "共 {0} 条", "{0} rules total", "共 {0} 條", "計 {0} 件", "총 {0}개", "{0} Regeln", "{0} reglas", "Всего {0} правил", "Toplam {0} kural", "{0} aturan", "مجموع {0} قانون", "{0} قاعدة إجمالًا", "Барлыгы {0} кагыйдә")

    # ---------- 日志 / 通用按钮 ----------
    k("Logs_Continue", "继续", "Resume", "繼續", "再開", "계속", "Fortsetzen", "Continuar", "Продолжить", "Devam et", "Lanjutkan", "ادامه", "متابعة", "Дәвам итү")

    # ---------- 热键冲突 ----------
    k("Hotkey_UnknownCombo", "{0}: 无法识别的组合键「{1}」", "{0}: unrecognized combo \"{1}\"", "{0}: 無法識別的組合鍵「{1}」", "{0}: 認識できないキー「{1}」", "{0}: 알 수 없는 조합 \"{1}\"", "{0}: unbekannte Kombination \"{1}\"", "{0}: combinación no reconocida \"{1}\"", "{0}: неизвестная комбинация \"{1}\"", "{0}: tanınmayan kombinasyon \"{1}\"", "{0}: kombinasi tidak dikenal \"{1}\"", "{0}: ترکیب ناشناس «{1}»", "{0}: مجموعة مفاتيح غير معروفة \"{1}\"", "{0}: билгесез комбиначия \"{1}\"")
    k("Hotkey_Duplicate", "{0}: 与「{1}」的热键冲突（{2}）", "{0}: conflicts with \"{1}\" ({2})", "{0}: 與「{1}」的熱鍵衝突（{2}）", "{0}: 「{1}」と競合（{2}）", "{0}: \"{1}\"과(와) 충돌({2})", "{0}: Konflikt mit \"{1}\" ({2})", "{0}: conflicto con \"{1}\" ({2})", "{0}: конфликт с \"{1}\" ({2})", "{0}: \"{1}\" ile çakışıyor ({2})", "{0}: bentrok dengan \"{1}\" ({2})", "{0}: با «{1}» تداخل دارد ({2})", "{0}: يتعارض مع \"{1}\" ({2})", "{0}: \"{1}\" белән конфликт ({2})")
    k("Hotkey_InUse", "{0}: 组合键「{1}」已被其他程序占用", "{0}: combo \"{1}\" is already in use", "{0}: 組合鍵「{1}」已被其他程式占用", "{0}: 「{1}」は使用中です", "{0}: \"{1}\"은(는) 이미 사용 중", "{0}: \"{1}\" wird bereits verwendet", "{0}: la combinación \"{1}\" ya está en uso", "{0}: комбинация \"{1}\" уже занята", "{0}: \"{1}\" zaten kullanımda", "{0}: \"{1}\" sudah digunakan", "{0}: ترکیب «{1}» اشغال است", "{0}: مجموعة المفاتيح \"{1}\" مستخدمة بالفعل", "{0}: \"{1}\" инде кулланылышта")

    # ---------- PrivilegeBroker ----------
    k("Priv_ActionStartCore", "通过服务启动内核", "Start core via service", "透過服務啟動核心", "サービス経由でコア起動", "서비스로 코어 시작", "Kern über Dienst starten", "Iniciar núcleo vía servicio", "Запуск ядра через службу", "Servis ile çekirdeği başlat", "Mulai core via layanan", "اجرای هسته از طریق سرویس", "تشغيل النواة عبر الخدمة", "Хезмәт аша йөзәк башлау")
    k("Priv_ActionStopCore", "通过服务停止内核", "Stop core via service", "透過服務停止核心", "サービス経由でコア停止", "서비스로 코어 중지", "Kern über Dienst stoppen", "Detener núcleo vía servicio", "Остановка ядра через службу", "Servis ile çekirdeği durdur", "Hentikan core via layanan", "توقف هسته از طریق سرویس", "إيقاف النواة عبر الخدمة", "Хезмәт аша йөзәкне туктату")
    k("Priv_ServiceUnavailable", "无法连接 Flux 服务", "Cannot connect to the Flux service", "無法連接 Flux 服務", "Fluxサービスに接続できません", "Flux 서비스에 연결할 수 없습니다", "Flux-Dienst nicht erreichbar", "No se puede conectar al servicio Flux", "Не удалось подключиться к службе Flux", "Flux servisine bağlanılamadı", "Tidak dapat terhubung ke layanan Flux", "اتصال به سرویس Flux ممکن نیست", "لا يمكن الاتصال بخدمة Flux", "Flux хезмәтенә тоташып булмады")
    k("Priv_VersionMismatch", "服务协议版本不匹配（服务 v{0}，应用 v{1}），请重启服务", "Service protocol version mismatch (service v{0}, app v{1}); restart the service", "服務協定版本不匹配（服務 v{0}，應用 v{1}），請重啟服務", "プロトコル版本不一致（サービスv{0}/アプリv{1}）。再起動してください", "프로토콜 버전 불일치(서비스 v{0}, 앱 v{1}). 서비스를 재시작하세요", "Protokollversion weicht ab (Dienst v{0}, App v{1}); Dienst neu starten", "Versión de protocolo incompatible (servicio v{0}, app v{1}); reinicie el servicio", "Несовпадение версии протокола (служба v{0}, приложение v{1}); перезапустите службу", "Protokol sürümü uyuşmuyor (servis v{0}, uygulama v{1}); servisi yeniden başlatın", "Versi protokol tidak cocok (layanan v{0}, app v{1}); mulai ulang layanan", "عدم تطابق نسخه پروتکل (سرویس v{0}، برنامه v{1})؛ سرویس را ری‌استارت کنید", "عدم تطابق إصدار البروتوكول (الخدمة v{0}، التطبيق v{1})؛ أعد تشغيل الخدمة", "Протокол версиясе туры килми (хезмәт v{0}, кушак v{1}); хезмәтне яңадан башлагыз")
    k("Priv_UnknownError", "未知服务错误", "Unknown service error", "未知服務錯誤", "不明なサービスエラー", "알 수 없는 서비스 오류", "Unbekannter Dienstfehler", "Error desconocido del servicio", "Неизвестная ошибка службы", "Bilinmeyen servis hatası", "Kesalahan layanan tidak diketahui", "خطای ناشناخته سرویس", "خطأ غير معروف في الخدمة", "Билгесез хезмәт хата")
    k("Priv_InstallerMissing", "未找到服务安装器，请重新安装应用", "Service installer not found; reinstall the app", "未找到服務安裝器，請重新安裝應用", "サービスインストーラーが見つかりません。再インストールしてください", "서비스 설치 관리자를 찾을 수 없습니다. 앱을 다시 설치하세요", "Dienst-Installer nicht gefunden; App neu installieren", "Instalador del servicio no encontrado; reinstale la app", "Установщик службы не найден; переустановите приложение", "Servis yükleyicisi bulunamadı; uygulamayı yeniden kurun", "Pemasang layanan tidak ditemukan; instal ulang aplikasi", "نصب‌کننده سرویس یافت نشد؛ برنامه را دوباره نصب کنید", "لم يُعثر على مثبّت الخدمة؛ أعد تثبيت التطبيق", "Хезмәт урнаштыргыч табылмады; кушакны кабат урнаштырыгыз")
    k("Priv_InstallerLaunchFailed", "无法启动安装器", "Failed to launch installer", "無法啟動安裝器", "インストーラーを起動できません", "설치 관리자를 시작할 수 없습니다", "Installer konnte nicht gestartet werden", "No se pudo iniciar el instalador", "Не удалось запустить установщик", "Yükleyici başlatılamadı", "Gagal meluncurkan pemasang", "راه‌اندازی نصب‌کننده ناموفق", "فشل تشغيل المثبّت", "Урнаштыргычны башлап булмады")
    k("Priv_InstallerExitCode", "安装器退出码 {0}（用户取消或安装失败）", "Installer exit code {0} (cancelled or failed)", "安裝器退出碼 {0}（使用者取消或安裝失敗）", "インストーラー終了コード {0}（取消または失敗）", "설치 관리자 종료 코드 {0}(취소 또는 실패)", "Installer-Exitcode {0} (abgebrochen oder fehlgeschlagen)", "Código de salida del instalador {0} (cancelado o fallido)", "Код выхода установщика {0} (отмена или сбой)", "Yükleyici çıkış kodu {0} (iptal veya başarısız)", "Kode keluar pemasang {0} (dibatalkan atau gagal)", "کد خروج نصب‌کننده {0} (لغو یا ناموفق)", "رمز خروج المثبّت {0} (أُلغي أو فشل)", "Урнаштыргыч коды {0} (кирекү яки хата)")
    k("Priv_NotReady", "服务已安装但未就绪", "Service installed but not ready", "服務已安裝但未就緒", "サービスはインストール済みだが未準備", "서비스가 설치되었지만 준비 안 됨", "Dienst installiert, aber nicht bereit", "Servicio instalado pero no listo", "Служба установлена, но не готова", "Servis kuruldu ama hazır değil", "Layanan terpasang tapi belum siap", "سرویس نصب شده اما آماده نیست", "الخدمة مثبتة لكنها غير جاهزة", "Хезмәт урнаштырылды ләкин әзер түгел")
    k("Priv_InstallStep", "服务安装", "Service install", "服務安裝", "サービスインストール", "서비스 설치", "Dienstinstallation", "Instalación del servicio", "Установка службы", "Servis kurulumu", "Instalasi layanan", "نصب سرویس", "تثبيت الخدمة", "Хезмәт урнаштыру")

    # ---------- WinInet ----------
    k("WinInet_NotifyFailed", "无法通知 Windows 系统代理设置已更改", "Failed to notify Windows of the proxy change", "無法通知 Windows 系統代理設定已變更", "Windowsへの変更通知に失敗", "Windows에 변경 알림 실패", "Windows konnte nicht benachrichtigt werden", "No se pudo notificar a Windows", "Не удалось уведомить Windows", "Windows'a bildirilemedi", "Gagal memberi tahu Windows", "اطلاع‌رسانی به ویندوز ناموفق بود", "فشل إشعار Windows بالتغيير", "Windows'ка хәбәр итеп булмады")
    k("WinInet_RefreshFailed", "无法刷新 Windows 系统代理设置", "Failed to refresh Windows proxy settings", "無法重新整理 Windows 系統代理設定", "プロキシ設定の更新に失敗", "프록시 설정 새로 고침 실패", "Proxy-Einstellungen konnten nicht aktualisiert werden", "No se pudo actualizar el proxy de Windows", "Не удалось обновить настройки прокси", "Proxy ayarları yenilenemedi", "Gagal menyegarkan pengaturan proxy", "بازخوانی تنظیمات پروکسی ناموفق", "فشل تحديث إعدادات البروكسي", "Прокси көйләүләрен яңарту хата")
    k("WinInet_ReadFailed", "无法读取 Windows 系统代理设置", "Failed to read Windows proxy settings", "無法讀取 Windows 系統代理設定", "プロキシ設定の読み取りに失敗", "프록시 설정 읽기 실패", "Proxy-Einstellungen konnten nicht gelesen werden", "No se pudo leer el proxy de Windows", "Не удалось прочитать настройки прокси", "Proxy ayarları okunamadı", "Gagal membaca pengaturan proxy", "خواندن تنظیمات پروکسی ناموفق", "فشل قراءة إعدادات البروكسي", "Прокси көйләүләрен уку хата")
    k("WinInet_WriteFailed", "无法修改 Windows 系统代理设置", "Failed to modify Windows proxy settings", "無法修改 Windows 系統代理設定", "プロキシ設定の変更に失敗", "프록시 설정 수정 실패", "Proxy-Einstellungen konnten nicht geändert werden", "No se pudo modificar el proxy de Windows", "Не удалось изменить настройки прокси", "Proxy ayarları değiştirilemedi", "Gagal mengubah pengaturan proxy", "تغییر تنظیمات پروکسی ناموفق", "فشل تعديل إعدادات البروكسي", "Прокси көйләүләрен үзгәртү хата")

    # ---------- App / 设置页剩余 ----------
    k("App_UnhandledUi", "UI 未处理异常: {0}", "UI unhandled exception: {0}", "UI 未處理例外: {0}", "UI未処理の例外: {0}", "UI 처리되지 않은 예외: {0}", "UI-Unbehandelte Ausnahme: {0}", "Excepción no controlada de UI: {0}", "Необработанное исключение UI: {0}", "UI işlenmeyen özel durum: {0}", "Pengecualian UI tidak tertangani: {0}", "استثنای پردازش‌نشده UI: {0}", "استثناء غير معالج في الواجهة: {0}", "UI эшкәртелмәгән искәртү: {0}")
    k("App_UnhandledDomain", "进程未处理异常: {0}", "Process unhandled exception: {0}", "處理程序未處理例外: {0}", "プロセス未処理の例外: {0}", "프로세스 처리되지 않은 예외: {0}", "Prozess-Unbehandelte Ausnahme: {0}", "Excepción no controlada del proceso: {0}", "Необработанное исключение процесса: {0}", "İşlem işlenmeyen özel durum: {0}", "Pengecualian proses tidak tertangani: {0}", "استثنای پردازش‌نشده فرایند: {0}", "استثناء غير معالج في العملية: {0}", "Процесс эшкәртелмәгән искәртү: {0}")
    k("App_UnobservedTask", "未观察任务异常: {0}", "Unobserved task exception: {0}", "未觀察工作例外: {0}", "未観察タスク例外: {0}", "관찰되지 않은 작업 예외: {0}", "Unbeobachtete Task-Ausnahme: {0}", "Excepción de tarea no observada: {0}", "Необработанное исключение задачи: {0}", "Gözlenmeyen görev özel durumu: {0}", "Pengecualian tugas tidak teramati: {0}", "استثنای مشاهده‌نشده تسک: {0}", "استثناء مهمة غير مراقب: {0}", "Күзәтелмәгән бурыч искәртүе: {0}")
    k("Settings_AppDescription", "基于 WinUI 3 的 Clash/Mihomo 客户端 · v{0}", "Clash/Mihomo client built on WinUI 3 · v{0}", "基於 WinUI 3 的 Clash/Mihomo 用戶端 · v{0}", "WinUI 3製Clash/Mihomoクライアント · v{0}", "WinUI 3 기반 Clash/Mihomo 클라이언트 · v{0}", "Clash/Mihomo-Client auf WinUI 3 · v{0}", "Cliente Clash/Mihomo basado en WinUI 3 · v{0}", "Клиент Clash/Mihomo на WinUI 3 · v{0}", "WinUI 3 tabanlı Clash/Mihomo istemcisi · v{0}", "Klien Clash/Mihomo berbasis WinUI 3 · v{0}", "کلاینت Clash/Mihomo مبتنی بر WinUI 3 · v{0}", "عميل Clash/Mihomo مبني على WinUI 3 · v{0}", "WinUI 3 нигезендәге Clash/Mihomo кушакы · v{0}")
    k("Settings_Unknown", "未知", "Unknown", "未知", "不明", "알 수 없음", "Unbekannt", "Desconocido", "Неизвестно", "Bilinmiyor", "Tidak diketahui", "نامشخص", "غير معروف", "Билгесез")
    k("Settings_AutoStartReadFailed", "读取自启动状态失败: {0}", "Failed to read auto-launch state: {0}", "讀取自啟動狀態失敗: {0}", "自動起動状態の取得に失敗: {0}", "자동 실행 상태 읽기 실패: {0}", "Autostart-Status konnte nicht gelesen werden: {0}", "Error al leer estado de autoinicio: {0}", "Ошибка чтения состояния автозапуска: {0}", "Otomatik başlatma durumu okunamadı: {0}", "Gagal membaca status mulai otomatis: {0}", "خواندن وضعیت اجرای خودکار ناموفق: {0}", "فشل قراءة حالة البدء التلقائي: {0}", "Автостарт халәтен уку хата: {0}")
    k("Settings_AutoStartFailed", "自启动设置失败: {0}", "Failed to set auto launch: {0}", "自啟動設定失敗: {0}", "自動起動の設定に失敗: {0}", "자동 실행 설정 실패: {0}", "Autostart fehlgeschlagen: {0}", "Error al configurar autoinicio: {0}", "Ошибка настройки автозапуска: {0}", "Otomatik başlatma ayarı başarısız: {0}", "Gagal mengatur mulai otomatis: {0}", "تنظیم اجرای خودکار ناموفق: {0}", "فشل إعداد البدء التلقائي: {0}", "Автостарт көйләү хата: {0}")
    k("Settings_AutoStartUpdateFailed", "更新自启动设置失败: {0}", "Failed to update auto launch: {0}", "更新自啟動設定失敗: {0}", "自動起動の更新に失敗: {0}", "자동 실행 업데이트 실패: {0}", "Autostart-Update fehlgeschlagen: {0}", "Error al actualizar autoinicio: {0}", "Ошибка обновления автозапуска: {0}", "Otomatik başlatma güncelleme başarısız: {0}", "Gagal memperbarui mulai otomatis: {0}", "به‌روزرسانی اجرای خودکار ناموفق: {0}", "فشل تحديث البدء التلقائي: {0}", "Автостарт яңарту хата: {0}")
    k("Settings_SysProxyFailed", "系统代理设置失败: {0}", "Failed to set system proxy: {0}", "系統代理設定失敗: {0}", "システムプロキシの設定に失敗: {0}", "시스템 프록시 설정 실패: {0}", "Systemproxy fehlgeschlagen: {0}", "Error al configurar proxy del sistema: {0}", "Ошибка настройки системного прокси: {0}", "Sistem proxy ayarı başarısız: {0}", "Gagal mengatur proxy sistem: {0}", "تنظیم پروکسی سیستم ناموفق: {0}", "فشل إعداد بروكسي النظام: {0}", "Систем прокси көйләү хата: {0}")
    k("Settings_PacFailed", "PAC 模式设置失败: {0}", "Failed to set PAC mode: {0}", "PAC 模式設定失敗: {0}", "PACモードの設定に失敗: {0}", "PAC 모드 설정 실패: {0}", "PAC-Modus fehlgeschlagen: {0}", "Error al configurar modo PAC: {0}", "Ошибка настройки режима PAC: {0}", "PAC modu ayarı başarısız: {0}", "Gagal mengatur mode PAC: {0}", "تنظیم حالت PAC ناموفق: {0}", "فشل إعداد وضع PAC: {0}", "PAC режимы көйләү хата: {0}")
    k("Settings_GuardFailed", "代理守护设置失败: {0}", "Failed to set proxy guard: {0}", "代理守護設定失敗: {0}", "プロキシガードの設定に失敗: {0}", "프록시 가드 설정 실패: {0}", "Proxy-Schutz fehlgeschlagen: {0}", "Error al configurar guardián: {0}", "Ошибка настройки защиты прокси: {0}", "Proxy koruması ayarı başarısız: {0}", "Gagal mengatur penjaga proxy: {0}", "تنظیم نگهبان پروکسی ناموفق: {0}", "فشل إعداد حارس البروكسي: {0}", "Прокси саклау көйләү хата: {0}")
    k("Settings_BypassFailed", "代理绕过设置失败: {0}", "Failed to set bypass list: {0}", "代理繞過設定失敗: {0}", "バイパスリストの設定に失敗: {0}", "우회 목록 설정 실패: {0}", "Bypass-Liste fehlgeschlagen: {0}", "Error al configurar exclusión: {0}", "Ошибка настройки списка исключений: {0}", "Bypass listesi ayarı başarısız: {0}", "Gagal mengatur daftar bypass: {0}", "تنظیم لیست دورزدن ناموفق: {0}", "فشل إعداد قائمة التجاوز: {0}", "Абход исемлеге көйләү хата: {0}")

    # ---------- 诊断报告 ----------
    k("Diag_Title", "=== Flux 诊断包 ===", "=== Flux Diagnostics ===", "=== Flux 診斷套件 ===", "=== Flux診断パック ===", "=== Flux 진단 패키지 ===", "=== Flux-Diagnose ===", "=== Diagnóstico de Flux ===", "=== Диагностика Flux ===", "=== Flux Teşhis Paketi ===", "=== Paket Diagnostik Flux ===", "=== بسته عیب‌یابی Flux ===", "=== حزمة تشخيص Flux ===", "=== Flux диагностика пакеты ===")
    k("Diag_ExportedAt", "导出时间: {0}", "Exported at: {0}", "匯出時間: {0}", "エクスポート日時: {0}", "내보낸 시간: {0}", "Exportiert: {0}", "Exportado: {0}", "Время экспорта: {0}", "Dışa aktarma zamanı: {0}", "Diekspor: {0}", "زمان خروجی: {0}", "وقت التصدير: {0}", "Чыгару вакыты: {0}")
    k("Diag_SectionSystem", "--- 系统信息 ---", "--- System ---", "--- 系統資訊 ---", "--- システム情報 ---", "--- 시스템 정보 ---", "--- System ---", "--- Sistema ---", "--- Система ---", "--- Sistem ---", "--- Sistem ---", "--- سیستم ---", "--- النظام ---", "--- Система ---")
    k("Diag_OsVersion", "OS 版本: {0}", "OS version: {0}", "OS 版本: {0}", "OSバージョン: {0}", "OS 버전: {0}", "BS-Version: {0}", "Versión del SO: {0}", "Версия ОС: {0}", "OS sürümü: {0}", "Versi OS: {0}", "نسخه سیستم‌عامل: {0}", "إصدار النظام: {0}", "ОС версиясе: {0}")
    k("Diag_Arch", "架构: {0}", "Architecture: {0}", "架構: {0}", "アーキテクチャ: {0}", "아키텍처: {0}", "Architektur: {0}", "Arquitectura: {0}", "Архитектура: {0}", "Mimari: {0}", "Arsitektur: {0}", "معماری: {0}", "المعمارية: {0}", "Архитектура: {0}")
    k("Diag_Processors", "处理器数: {0}", "Processors: {0}", "處理器數: {0}", "プロセッサ数: {0}", "프로세서 수: {0}", "Prozessoren: {0}", "Procesadores: {0}", "Процессоров: {0}", "İşlemci sayısı: {0}", "Jumlah prosesor: {0}", "تعداد پردازنده: {0}", "عدد المعالجات: {0}", "Процессорлар саны: {0}")
    k("Diag_FluxVersion", "Flux 版本: {0}", "Flux version: {0}", "Flux 版本: {0}", "Fluxバージョン: {0}", "Flux 버전: {0}", "Flux-Version: {0}", "Versión de Flux: {0}", "Версия Flux: {0}", "Flux sürümü: {0}", "Versi Flux: {0}", "نسخه Flux: {0}", "إصدار Flux: {0}", "Flux версиясе: {0}")
    k("Diag_RunMode", "运行模式: {0}", "Run mode: {0}", "執行模式: {0}", "実行モード: {0}", "실행 모드: {0}", "Ausführungsmodus: {0}", "Modo de ejecución: {0}", "Режим запуска: {0}", "Çalışma modu: {0}", "Mode berjalan: {0}", "حالت اجرا: {0}", "وضع التشغيل: {0}", "Эш режимы: {0}")
    k("Diag_Admin", "管理员: {0}", "Administrator: {0}", "管理員: {0}", "管理者: {0}", "관리자: {0}", "Administrator: {0}", "Administrador: {0}", "Администратор: {0}", "Yönetici: {0}", "Administrator: {0}", "مدیر: {0}", "مسؤول: {0}", "Администратор: {0}")
    k("Diag_SectionCore", "--- 内核 ---", "--- Core ---", "--- 核心 ---", "--- コア ---", "--- 코어 ---", "--- Kern ---", "--- Núcleo ---", "--- Ядро ---", "--- Çekirdek ---", "--- Core ---", "--- هسته ---", "--- النواة ---", "--- Йөзәк ---")
    k("Diag_CoreVersion", "mihomo 版本: {0}", "mihomo version: {0}", "mihomo 版本: {0}", "mihomoバージョン: {0}", "mihomo 버전: {0}", "mihomo-Version: {0}", "Versión de mihomo: {0}", "Версия mihomo: {0}", "mihomo sürümü: {0}", "Versi mihomo: {0}", "نسخه mihomo: {0}", "إصدار mihomo: {0}", "mihomo версиясе: {0}")
    k("Diag_CoreVersionFailed", "mihomo 版本: 获取失败 ({0})", "mihomo version: failed to get ({0})", "mihomo 版本: 取得失敗 ({0})", "mihomoバージョン: 取得失敗 ({0})", "mihomo 버전: 가져오기 실패({0})", "mihomo-Version: Abruf fehlgeschlagen ({0})", "Versión de mihomo: error al obtener ({0})", "Версия mihomo: ошибка получения ({0})", "mihomo sürümü: alınamadı ({0})", "Versi mihomo: gagal mendapat ({0})", "نسخه mihomo: دریافت ناموفق ({0})", "إصدار mihomo: فشل الجلب ({0})", "mihomo версиясе: алу хата ({0})")
    k("Diag_CoreMode", "内核模式: {0}", "Core mode: {0}", "核心模式: {0}", "コアモード: {0}", "코어 모드: {0}", "Kern-Modus: {0}", "Modo del núcleo: {0}", "Режим ядра: {0}", "Çekirdek modu: {0}", "Mode core: {0}", "حالت هسته: {0}", "وضع النواة: {0}", "Йөзәк режимы: {0}")
    k("Diag_ServiceState", "服务状态: {0}", "Service state: {0}", "服務狀態: {0}", "サービス状態: {0}", "서비스 상태: {0}", "Dienststatus: {0}", "Estado del servicio: {0}", "Состояние службы: {0}", "Servis durumu: {0}", "Status layanan: {0}", "وضعیت سرویس: {0}", "حالة الخدمة: {0}", "Хезмәт хәле: {0}")
    k("Diag_SectionConfig", "--- 配置结构（敏感字段已遮蔽） ---", "--- Config structure (sensitive fields masked) ---", "--- 設定結構（敏感欄位已遮蔽） ---", "--- 設定構造（機密項目はマスク） ---", "--- 설정 구조(민감 항목 마스킹) ---", "--- Konfigstruktur (sensible Felder maskiert) ---", "--- Estructura de configuración (campos sensibles ocultos) ---", "--- Структура конфигурации (скрыто) ---", "--- Yapılandırma yapısı (hassas alanlar maskeli) ---", "--- Struktur konfigurasi (bidang sensitif disamarkan) ---", "--- ساختار پیکربندی (فیلدهای حساس پوشانده شده) ---", "--- بنية التكوين (الحقول الحساسة مخفية) ---", "--- Конфигурация (серler яшерелгән) ---")
    k("Diag_CurrentProfile", "当前订阅: {0}", "Current profile: {0}", "目前訂閱: {0}", "現在の購読: {0}", "현재 구독: {0}", "Aktuelles Profil: {0}", "Perfil actual: {0}", "Текущая подписка: {0}", "Mevcut profil: {0}", "Profil saat ini: {0}", "پروفایل فعلی: {0}", "الملف الحالي: {0}", "Хәзерге профиль: {0}")
    k("Diag_SectionRuntime", "--- 运行设置摘要 ---", "--- Runtime settings summary ---", "--- 執行設定摘要 ---", "--- 実行設定サマリ ---", "--- 실행 설정 요약 ---", "--- Laufzeiteinstellungen ---", "--- Resumen de ajustes de ejecución ---", "--- Сводка настроек ---", "--- Çalışma ayarları özeti ---", "--- Ringkasan pengaturan ---", "--- خلاصه تنظیمات اجرا ---", "--- ملخص إعدادات التشغيل ---", "--- Эш көйләүләре йомгагы ---")
    k("Diag_SystemProxyLine", "系统代理: {0} (PAC: {1})", "System proxy: {0} (PAC: {1})", "系統代理: {0} (PAC: {1})", "システムプロキシ: {0} (PAC: {1})", "시스템 프록시: {0} (PAC: {1})", "Systemproxy: {0} (PAC: {1})", "Proxy del sistema: {0} (PAC: {1})", "Системный прокси: {0} (PAC: {1})", "Sistem proxy: {0} (PAC: {1})", "Proxy sistem: {0} (PAC: {1})", "پروکسی سیستم: {0} (PAC: {1})", "بروكسي النظام: {0} (PAC: {1})", "Систем прокси: {0} (PAC: {1})")
    k("Diag_SectionLogs", "--- 最近应用日志（200 条，敏感信息已遮蔽） ---", "--- Recent app logs (200, masked) ---", "--- 最近應用日誌（200 條，敏感資訊已遮蔽） ---", "--- 直近アプリログ(200件、マスク済み) ---", "--- 최근 앱 로그(200개, 마스킹) ---", "--- Letzte Logs (200, maskiert) ---", "--- Registros recientes (200, ocultos) ---", "--- Последние журналы (200, скрыто) ---", "--- Son uygulama kayıtları (200, maskeli) ---", "--- Log aplikasi terbaru (200, disamarkan) ---", "--- گزارش‌های اخیر (۲۰۰ مورد، پوشانده شده) ---", "--- أحدث السجلات (200، مخفية) ---", "--- Соңгы журналлар (200, яшерелгән) ---")
    k("Diag_NoLogFile", "(无应用日志文件)", "(no app log file)", "(無應用日誌檔案)", "(アプリログなし)", "(앱 로그 파일 없음)", "(keine Logdatei)", "(sin archivo de log)", "(нет файла журнала)", "(uygulama kayıt dosyası yok)", "(tidak ada file log)", "(فایل گزارش برنامه نیست)", "(لا يوجد ملف سجل)", "(кушак журналы юк)")
    k("Diag_LogReadFailed", "(日志读取失败: {0})", "(failed to read logs: {0})", "(日誌讀取失敗: {0})", "(ログ読み取り失敗: {0})", "(로그 읽기 실패: {0})", "(Logs konnten nicht gelesen werden: {0})", "(error al leer logs: {0})", "(ошибка чтения журналов: {0})", "Kayıtlar okunamadı: {0}", "(gagal membaca log: {0})", "(خواندن گزارش‌ها ناموفق: {0})", "(فشل قراءة السجلات: {0})", "(журналларны уку хата: {0})")
    k("Diag_Exported", "诊断包已导出: {0}", "Diagnostics exported: {0}", "診斷套件已匯出: {0}", "診断をエクスポートしました: {0}", "진단 패키지 내보냄: {0}", "Diagnose exportiert: {0}", "Diagnóstico exportado: {0}", "Диагностика экспортирована: {0}", "Teşhis dışa aktarıldı: {0}", "Diagnostik diekspor: {0}", "عیب‌یابی صادر شد: {0}", "تم تصدير التشخيص: {0}", "Диагностика чыгарылды: {0}")
    k("Diag_MaskedValue", "（已遮蔽）", "(masked)", "（已遮蔽）", "（マスク済み）", "（마스킹됨）", "(maskiert)", "(oculto)", "(скрыто)", "(maskeli)", "(disamarkan)", "（پوشانده شده）", "(مخفي)", "(яшерелгән)")
    k("Enhance_YamlSyntaxError", "YAML 语法错误: {0}（必须是键值映射）", "YAML syntax error in {0} (must be a key-value mapping)", "YAML 語法錯誤: {0}（必須是鍵值映射）", "YAML構文エラー: {0}（キー値マップである必要）", "YAML 구문 오류: {0}(키-값 매핑이어야 함)", "YAML-Syntaxfehler in {0} (Mapping erforderlich)", "Error de sintaxis YAML en {0} (debe ser un mapeo)", "Синтаксическая ошибка YAML в {0} (нужен mapping)", "{0} içinde YAML sözdizimi hatası (eşleme olmalı)", "Kesalahan sintaks YAML di {0} (harus berupa pemetaan)", "خطای نحو YAML در {0} (باید نگاشت باشد)", "خطأ في صياغة YAML في {0} (يجب أن يكون تعيينًا)", "{0} эчендә YAML синтаксис хата (mapping булырга тиеш)")
    k("Boot_HotkeyModeSwitch", "热键切换模式: {0}", "Hotkey switched mode: {0}", "熱鍵切換模式: {0}", "ホットキーでモード切替: {0}", "단축키 모드 전환: {0}", "Hotkey-Moduswechsel: {0}", "Atajo cambió modo: {0}", "Горячая клавиша сменила режим: {0}", "Kısayol mod değiştirdi: {0}", "Pintasan mengganti mode: {0}", "میانبر حالت را عوض کرد: {0}", "الاختصار غيّر الوضع: {0}", "Кыска юл режимны алмаштырды: {0}")
    k("Settings_LangFollowSystem", "跟随系统", "Follow system", "跟隨系統", "システムに従う", "시스템 따르기", "System folgen", "Según el sistema", "Как в системе", "Sistemi takip et", "Ikuti sistem", "بر اساس سیستم", "حسب النظام", "Система буенча")
    k("App_ShutdownFailed", "退出清理失败: {0}", "Shutdown cleanup failed: {0}", "退出清理失敗: {0}", "シャットダウン清理に失敗: {0}", "종료 정리 실패: {0}", "Cleanup beim Beenden fehlgeschlagen: {0}", "Error al limpiar al salir: {0}", "Ошибка очистки при выходе: {0}", "Çıkış temizliği başarısız: {0}", "Gagal membersihkan saat keluar: {0}", "پاک‌سازی خروج ناموفق: {0}", "فشل تنظيف الخروج: {0}", "Чыгу чистарту хата: {0}")
    k("Config_RuntimeGenFailed", "运行时配置合成失败", "Runtime config generation failed", "執行時設定合成失敗", "実行時設定の合成に失敗", "런타임 설정 합성 실패", "Laufzeitkonfiguration fehlgeschlagen", "Error al generar configuración", "Ошибка генерации конфигурации", "Çalışma yapılandırması oluşturulamadı", "Gagal membuat konfigurasi", "تولید پیکربندی runtime ناموفق", "فشل توليد تكوين التشغيل", "Runtime конфигурация ясау хата")
    k("Config_TargetDirMissing", "目标文件缺少目录", "Target file has no directory", "目標檔案缺少目錄", "対象ファイルにディレクトリがない", "대상 파일에 디렉터리 없음", "Zieldatei ohne Verzeichnis", "El archivo de destino no tiene directorio", "У целевого файла нет каталога", "Hedef dosyanın klasörü yok", "File target tidak punya direktori", "فایل مقصد فاقد پوشه است", "الملف الهدف بلا مجلد", "Максат файлында папка юк")
