# -*- coding: utf-8 -*-
"""核心服务层 LogService/异常消息 i18n 键表（由 gen_i18n.py 调用 register(k)）。"""


def register(k):
    # ---------- CoreProcessService ----------
    k("Core_StartedService", "mihomo 内核已由服务以特权模式启动", "mihomo core started in privileged service mode", "mihomo 核心已由服務以特權模式啟動", "mihomoコアをサービス特権モードで起動", "mihomo 코어가 서비스 특권 모드로 시작됨", "mihomo-Kern im privilegierten Dienstmodus gestartet", "Núcleo mihomo iniciado en modo servicio privilegiado", "Ядро mihomo запущено в привилегированном режиме службы", "mihomo çekirdeği ayrıcalıklı servis modunda başlatıldı", "Core mihomo dimulai dalam mode layanan istimewa", "هسته mihomo در حالت سرویس ممتاز اجرا شد", "تم تشغيل نواة mihomo بوضع الخدمة المميز", "mihomo йөзәге хезмәт привилегиялы режимында башланды")
    k("Core_ServiceStartFailedFallback", "服务模式启动失败，回退应用内模式: {0}", "Service mode start failed, falling back to sidecar: {0}", "服務模式啟動失敗，回退應用內模式: {0}", "サービスモード起動に失敗、サイドカーへ切替: {0}", "서비스 모드 시작 실패, 사이드카로 전환: {0}", "Dienstmodus fehlgeschlagen, Fallback auf Sidecar: {0}", "Fallo del modo servicio, retroceso a sidecar: {0}", "Не удалось запустить службу, возврат к sidecar: {0}", "Servis modu başlatılamadı, sidecar'a dönülüyor: {0}", "Mode layanan gagal, fallback ke sidecar: {0}", "راه‌اندازی حالت سرویس ناموفق، بازگشت به حالت داخلی: {0}", "فشل تشغيل وضع الخدمة، الرجوع للوضع الداخلي: {0}", "Хезмәт режимы хата, sidecar'га кайту: {0}")
    k("Core_Started", "mihomo 内核已启动", "mihomo core started", "mihomo 核心已啟動", "mihomoコアを起動しました", "mihomo 코어 시작됨", "mihomo-Kern gestartet", "Núcleo mihomo iniciado", "Ядро mihomo запущено", "mihomo çekirdeği başlatıldı", "Core mihomo dimulai", "هسته mihomo اجرا شد", "تم تشغيل نواة mihomo", "mihomo йөзәге башланды")
    k("Core_StopViaServiceFailed", "服务停止内核失败: {0}", "Service failed to stop core: {0}", "服務停止核心失敗: {0}", "サービス停止に失敗: {0}", "서비스 코어 중지 실패: {0}", "Dienst konnte Kern nicht stoppen: {0}", "El servicio no pudo detener el núcleo: {0}", "Служба не смогла остановить ядро: {0}", "Servis çekirdeği durduramadı: {0}", "Layanan gagal menghentikan core: {0}", "سرویس نتوانست هسته را متوقف کند: {0}", "فشلت الخدمة في إيقاف النواة: {0}", "Хезмәт йөзәкне туктата алмады: {0}")
    k("Core_KillLeftover", "已清理残留内核进程 PID {0}", "Cleaned up leftover core process PID {0}", "已清理殘留核心程式 PID {0}", "残存コアプロセスを終了 PID {0}", "남은 코어 프로세스 정리 PID {0}", "Übrig gebliebenen Kernprozess beendet PID {0}", "Proceso residual limpiado PID {0}", "Остановлен остаточный процесс ядра PID {0}", "Artık çekirdek süreci temizlendi PID {0}", "Proses core tersisa dibersihkan PID {0}", "فرایند باقی‌مانده هسته پاکسازی شد PID {0}", "نظّفت عملية النواة المتبقية PID {0}", "Калдык процесс тәмамланды PID {0}")
    k("Core_ApplyRejected", "配置应用被拒绝: {0}", "Config apply rejected: {0}", "設定應用被拒絕: {0}", "設定適用が拒否: {0}", "설정 적용 거부됨: {0}", "Konfiguration abgelehnt: {0}", "Configuración rechazada: {0}", "Применение конфигурации отклонено: {0}", "Yapılandırma reddedildi: {0}", "Penerapan konfigurasi ditolak: {0}", "پیکربندی رد شد: {0}", "تم رفض تطبيق التكوين: {0}", "Конфигурация кабул ителмәде: {0}")
    k("Core_HotReloaded", "运行时配置已热重载", "Runtime config hot-reloaded", "執行時設定已熱重載", "実行時設定をホットリロード", "런타임 설정 핫 리로드", "Laufzeitkonfiguration hot-reloaded", "Configuración recargada en caliente", "Конфигурация горячо перезагружена", "Çalışma yapılandırması hot-reload edildi", "Konfigurasi dimuat ulang", "پیکربندی runtime بازخوانی شد", "أعيد تحميل تكوين التشغيل", "Runtime конфигурация яңартылды")
    k("Core_HotReloadFailedRestart", "热重载失败，重启内核: {0}", "Hot-reload failed, restarting core: {0}", "熱重載失敗，重啟核心: {0}", "ホットリロード失敗、再起動: {0}", "핫 리로드 실패, 재시작: {0}", "Hot-Reload fehlgeschlagen, Neustart: {0}", "Recarga fallida, reiniciando núcleo: {0}", "Горячая перезагрузка не удалась, перезапуск: {0}", "Hot-reload başarısız, yeniden başlatılıyor: {0}", "Hot-reload gagal, merestart core: {0}", "بازخوانی ناموفق، ری‌استارت هسته: {0}", "فشل إعادة التحميل، إعادة تشغيل النواة: {0}", "Яңарту хата, йөзәкне яңадан башлау: {0}")
    k("Core_RestoreSelectionsFailed", "恢复节点选择失败: {0}", "Failed to restore node selections: {0}", "恢復節點選擇失敗: {0}", "ノード選択の復元に失敗: {0}", "노드 선택 복원 실패: {0}", "Knotenauswahl wiederherstellen fehlgeschlagen: {0}", "Error al restaurar nodos: {0}", "Ошибка восстановления выборов узлов: {0}", "Düğüm seçimi geri yükleme başarısız: {0}", "Gagal memulihkan pilihan node: {0}", "بازیابی انتخاب گره ناموفق: {0}", "فشل استعادة اختيارات العقد: {0}", "Төен сайлауларын кайтару хата: {0}")
    k("Core_RestoredSelection", "已恢复节点选择: {0} → {1}", "Restored node selection: {0} → {1}", "已恢復節點選擇: {0} → {1}", "ノード選択を復元: {0} → {1}", "노드 선택 복원: {0} → {1}", "Knotenauswahl wiederhergestellt: {0} → {1}", "Selección restaurada: {0} → {1}", "Выбор узла восстановлен: {0} → {1}", "Düğüm seçimi geri yüklendi: {0} → {1}", "Pilihan node dipulihkan: {0} → {1}", "انتخاب گره بازیابی شد: {0} → {1}", "استُعيد اختيار العقدة: {0} → {1}", "Төен сайлавы кайтарылды: {0} → {1}")
    k("Core_SelectionMissing", "有 {0} 个已保存节点在当前配置中不存在，已跳过恢复", "{0} saved nodes missing from current config; restore skipped", "有 {0} 個已儲存節點在目前設定中不存在，已跳過恢復", "保存済みノード{0}個が現在の設定に存在しません", "저장된 노드 {0}개가 현재 설정에 없습니다", "{0} gespeicherte Knoten fehlen; Überspringen", "{0} nodos guardados no existen; se omitió la restauración", "{0} сохранённых узлов отсутствуют; восстановление пропущено", "Kayıtlı {0} düğüm mevcut yapılandırmada yok; atlandı", "{0} node tersimpan tidak ada; pemulihan dilewati", "{0} گره ذخیره‌شده در پیکربندی نیست؛ بازیابی رد شد", "{0} عقدة محفوظة غير موجودة؛ تم تخطي الاستعادة", "{0} сакланган төен юк; кайтару уздырылды")
    k("Core_JobAssignFailed", "Job Object 关联失败，主进程异常退出时内核可能残留", "Job Object assignment failed; core may linger if the app crashes", "Job Object 關聯失敗，主程式異常退出時核心可能殘留", "Job Objectの関連付けに失敗。異常終了時にコアが残る可能性", "Job Object 연결 실패, 비정상 종료 시 코어 잔류 가능", "Job Object fehlgeschlagen; Kern könnte überleben", "Fallo al asignar Job Object; el núcleo podría quedar residual", "Не удалось привязать Job Object; ядро может остаться", "Job Object atanamadı; çekirdek kalabilir", "Gagal menautkan Job Object; core bisa tertinggal", "اتصال Job Object ناموفق؛ هسته ممکن است باقی بماند", "فشل ربط Job Object؛ قد تبقى النواة", "Job Object бәйләү хата; йөзәк калып калырга мөмкин")
    k("Core_ProcessStartFailed", "mihomo 进程启动失败", "Failed to start mihomo process", "mihomo 程式啟動失敗", "mihomoプロセスの起動に失敗", "mihomo 프로세스 시작 실패", "mihomo-Prozessstart fehlgeschlagen", "Error al iniciar proceso mihomo", "Не удалось запустить процесс mihomo", "mihomo süreci başlatılamadı", "Gagal memulai proses mihomo", "اجرای فرایند mihomo ناموفق", "فشل بدء عملية mihomo", "mihomo процесын башлау хата")
    k("Core_ValidateFailed", "配置校验失败: {0}", "Config validation failed: {0}", "設定校驗失敗: {0}", "設定検証に失敗: {0}", "설정 검증 실패: {0}", "Konfigurationsvalidierung fehlgeschlagen: {0}", "Validación de configuración fallida: {0}", "Ошибка проверки конфигурации: {0}", "Yapılandırma doğrulaması başarısız: {0}", "Validasi konfigurasi gagal: {0}", "اعتبارسنجی پیکربندی ناموفق: {0}", "فشل التحقق من التكوين: {0}", "Конфигурация тикшерүе хата: {0}")
    k("Core_ProcessExited", "mihomo 进程异常退出，请查看日志", "mihomo process exited unexpectedly; check the logs", "mihomo 程式異常退出，請查看日誌", "mihomoが異常終了しました。ログを確認", "mihomo가 비정상 종료되었습니다. 로그를 확인하세요", "mihomo unerwartet beendet; Protokolle prüfen", "mihomo terminó inesperadamente; revise los registros", "mihomo аварийно завершился; проверьте журналы", "mihomo beklenmedik şekilde çıktı; kayıtları inceleyin", "mihomo berhenti tak terduga; periksa log", "mihomo غیرعادی خارج شد؛ گزارش‌ها را بررسی کنید", "خرج mihomo بشكل غير متوقع؛ راجع السجلات", "mihomo көтелмәгәнлектән чыкты; журналларны карагыз")
    k("Core_ControllerTimeout", "等待 External Controller 就绪超时", "Timed out waiting for External Controller", "等待 External Controller 就緒逾時", "External Controllerの起動待ちがタイムアウト", "External Controller 대기 시간 초과", "Timeout beim Warten auf den External Controller", "Tiempo de espera agotado para el External Controller", "Таймаут ожидания External Controller", "External Controller bekleme zaman aşımı", "Menunggu External Controller mengalami timeout", "انتظار برای External Controller به پایان رسید", "انتهت مهلة انتظار External Controller", "External Controller көтү вакыты тулды")
    k("Core_Pid", "mihomo PID: {0}", "mihomo PID: {0}", "mihomo PID: {0}", "mihomo PID: {0}", "mihomo PID: {0}", "mihomo PID: {0}", "PID de mihomo: {0}", "mihomo PID: {0}", "mihomo PID: {0}", "mihomo PID: {0}", "mihomo PID: {0}", "mihomo PID: {0}", "mihomo PID: {0}")

    # ---------- SysProxyService ----------
    k("Proxy_Restored", "系统代理已恢复", "System proxy restored", "系統代理已恢復", "システムプロキシを復元", "시스템 프록시 복원됨", "Systemproxy wiederhergestellt", "Proxy del sistema restaurado", "Системный прокси восстановлен", "Sistem proxy geri yüklendi", "Proxy sistem dipulihkan", "پروکسی سیستم بازیابی شد", "تمت استعادة بروكسي النظام", "Систем прокси кайтарылды")
    k("Proxy_Enabled", "系统代理已开启: {0}", "System proxy enabled: {0}", "系統代理已開啟: {0}", "システムプロキシ有効化: {0}", "시스템 프록시 켜짐: {0}", "Systemproxy aktiviert: {0}", "Proxy del sistema activado: {0}", "Системный прокси включён: {0}", "Sistem proxy açıldı: {0}", "Proxy sistem aktif: {0}", "پروکسی سیستم فعال شد: {0}", "تم تفعيل بروكسي النظام: {0}", "Систем прокси ачылды: {0}")
    k("Proxy_EnabledPac", "系统代理已开启（PAC 模式）: {0}", "System proxy enabled (PAC mode): {0}", "系統代理已開啟（PAC 模式）: {0}", "システムプロキシ有効化（PACモード）: {0}", "시스템 프록시 켜짐(PAC 모드): {0}", "Systemproxy aktiviert (PAC): {0}", "Proxy activado (modo PAC): {0}", "Системный прокси включён (PAC): {0}", "Sistem proxy açıldı (PAC modu): {0}", "Proxy sistem aktif (mode PAC): {0}", "پروکسی سیستم فعال شد (حالت PAC): {0}", "تم تفعيل بروكسي النظام (وضع PAC): {0}", "Систем прокси ачылды (PAC режимы): {0}")
    k("Proxy_StaleRestored", "检测到上次未恢复的系统代理，已恢复原始设置", "Detected unrestored system proxy from last session; original settings restored", "偵測到上次未恢復的系統代理，已恢復原始設定", "前回の未復元プロキシを検出し復元しました", "이전 세션의 미복원 프록시 감지, 원래 설정 복원", "Nicht restaurierten Proxy erkannt; Originaleinstellungen wiederhergestellt", "Detectado proxy sin restaurar; se restauró la configuración original", "Обнаружен не восстановленный прокси; настройки восстановлены", "Önceki oturumdan kalma proxy algılandı; orijinal ayarlar geri yüklendi", "Proxy dari sesi sebelumnya terdeteksi; pengaturan asli dipulihkan", "پروکسی بازیابی‌نشده جلسه قبل شناسایی شد؛ تنظیمات اصلی بازیابی شد", "اكتُشف بروكسي غير مستعاد من الجلسة السابقة؛ استُعيدت الإعدادات الأصلية", "Соңгы сеанстың проксиесе табылды; төп көйләүләр кайтарылды")
    k("Proxy_LegacyDisabled", "检测到旧版本遗留的系统代理，已自动关闭", "Detected stale proxy from an older version; disabled automatically", "偵測到舊版本遺留的系統代理，已自動關閉", "旧バージョンの残存プロキシを検出し無効化", "이전 버전의 잔여 프록시 감지, 자동으로 끔", "Veralteter Proxy erkannt; automatisch deaktiviert", "Proxy de versión anterior detectado; desactivado", "Обнаружен прокси от старой версии; отключён", "Eski sürümden kalan proxy algılandı; otomatik kapatıldı", "Proxy dari versi lama terdeteksi; dimatikan otomatis", "پروکسی نسخه قدیمی شناسایی شد؛ خودکار خاموش شد", "اكتُشف بروكسي من إصدار قديم؛ عُطّل تلقائيًا", "Иске версиядән прокси табылды; автоматик рәвештә сүндерелде")
    k("Proxy_StaleRestoreFailed", "恢复遗留系统代理失败: {0}", "Failed to restore stale proxy: {0}", "恢復遺留系統代理失敗: {0}", "残存プロキシの復元に失敗: {0}", "잔여 프록시 복원 실패: {0}", "Veralteter Proxy konnte nicht restauriert werden: {0}", "Error al restaurar proxy residual: {0}", "Не удалось восстановить остаточный прокси: {0}", "Kalıntı proxy geri yükleme başarısız: {0}", "Gagal memulihkan proxy tersisa: {0}", "بازیابی پروکسی باقی‌مانده ناموفق: {0}", "فشل استعادة البروكسي المتبقي: {0}", "Калдык проксины кайтару хата: {0}")
    k("Proxy_ChangedByOther", "系统代理已被其他程序修改，Flux 不再覆盖该设置", "System proxy was changed by another program; Flux will not overwrite it", "系統代理已被其他程式修改，Flux 不再覆蓋該設定", "他プログラムが変更したため上書きしません", "다른 프로그램이 변경하여 더 이상 덮어쓰지 않습니다", "Systemproxy wurde extern geändert; Flux überschreibt nicht", "El proxy fue modificado por otro programa; Flux no lo sobrescribirá", "Системный прокси изменён другой программой; Flux не перезапишет", "Sistem proxy başka bir program tarafından değiştirildi; üzerine yazılmayacak", "Proxy sistem diubah program lain; Flux tidak menimpanya", "پروکسی سیستم توسط برنامه دیگری تغییر کرد؛ Flux بازنویسی نمی‌کند", "تم تعديل بروكسي النظام بواسطة برنامج آخر؛ لن يستبدله Flux", "Систем проксины башка программа үзгәртте; Flux кабат язмаячак")
    k("Proxy_SnapshotReadFailed", "系统代理快照读取失败: {0}", "Failed to read proxy snapshot: {0}", "系統代理快照讀取失敗: {0}", "プロキシスナップショットの読み取り失敗: {0}", "프록시 스냅샷 읽기 실패: {0}", "Proxy-Snapshot lesbar nicht: {0}", "Error al leer la instantánea del proxy: {0}", "Ошибка чтения снимка прокси: {0}", "Proxy anlık görüntüsü okunamadı: {0}", "Gagal membaca snapshot proxy: {0}", "خواندن اسنپ‌شات پروکسی ناموفق: {0}", "فشل قراءة لقطة البروكسي: {0}", "Прокси снимогын уку хата: {0}")
    k("Proxy_ChangedRestoring", "检测到系统代理被修改，正在恢复", "System proxy changed externally; restoring", "偵測到系統代理被修改，正在恢復", "システムプロキシの外部変更を検出、復元中", "시스템 프록시 변경 감지, 복원 중", "Externe Proxy-Änderung erkannt; wird wiederhergestellt", "Cambio externo del proxy detectado; restaurando", "Обнаружено внешнее изменение прокси; восстановление", "Sistem proxy harici değiştirildi; geri yükleniyor", "Perubahan proxy eksternal terdeteksi; memulihkan", "تغییر خارجی پروکسی سیستم شناسایی شد؛ در حال بازیابی", "اكتُشف تعديل خارجي للبروكسي؛ جارٍ الاستعادة", "Проксины тышкы үзгәртү табылды; кайтартыла")
    k("Proxy_GuardError", "代理守护异常: {0}", "Proxy guard error: {0}", "代理守護異常: {0}", "プロキシガード異常: {0}", "프록시 가드 오류: {0}", "Proxy-Schutz-Fehler: {0}", "Error del guardián del proxy: {0}", "Ошибка защиты прокси: {0}", "Proxy koruma hatası: {0}", "Kesalahan penjaga proxy: {0}", "خطای نگهبان پروکسی: {0}", "خطأ في حارس البروكسي: {0}", "Прокси саклау хата: {0}")

    # ---------- ConfigService ----------
    k("Config_VergeLoadFailed", "verge.yaml 加载失败: {0}", "Failed to load verge.yaml: {0}", "verge.yaml 載入失敗: {0}", "verge.yamlの読み込み失敗: {0}", "verge.yaml 로드 실패: {0}", "verge.yaml konnte nicht geladen werden: {0}", "Error al cargar verge.yaml: {0}", "Ошибка загрузки verge.yaml: {0}", "verge.yaml yüklenemedi: {0}", "Gagal memuat verge.yaml: {0}", "بارگذاری verge.yaml ناموفق: {0}", "فشل تحميل verge.yaml: {0}", "verge.yaml йөкләү хата: {0}")
    k("Config_VergeMigrateBackupFailed", "verge.yaml 迁移备份失败: {0}", "verge.yaml migration backup failed: {0}", "verge.yaml 遷移備份失敗: {0}", "verge.yaml移行バックアップ失敗: {0}", "verge.yaml 마이그레이션 백업 실패: {0}", "verge.yaml Migrations-Backup fehlgeschlagen: {0}", "Error de respaldo de migración de verge.yaml: {0}", "Ошибка резервной копии миграции verge.yaml: {0}", "verge.yaml geçiş yedeği başarısız: {0}", "Gagal backup migrasi verge.yaml: {0}", "پشتیبان‌گیری مهاجرت verge.yaml ناموفق: {0}", "فشل نسخة ترحيل verge.yaml: {0}", "verge.yaml миграция резервы хата: {0}")
    k("Config_VergeMigrated", "verge.yaml 已迁移至 schema v{0}，备份: {1}", "verge.yaml migrated to schema v{0}; backup: {1}", "verge.yaml 已遷移至 schema v{0}，備份: {1}", "verge.yamlをスキーマv{0}へ移行、バックアップ: {1}", "verge.yaml이 schema v{0}(으)로 마이그레이션, 백업: {1}", "verge.yaml auf Schema v{0} migriert; Backup: {1}", "verge.yaml migrado a esquema v{0}; copia: {1}", "verge.yaml мигрирован на схему v{0}; копия: {1}", "verge.yaml şema v{0}'a taşındı; yedek: {1}", "verge.yaml dimigrasi ke skema v{0}; cadangan: {1}", "verge.yaml به اسکیمای v{0} منتقل شد؛ پشتیبان: {1}", "تم ترحيل verge.yaml إلى المخطط v{0}؛ النسخة: {1}", "verge.yaml schema v{0}'ка миграцияланды; резерв: {1}")
    k("Config_ClashLoadFailed", "config.yaml 加载失败: {0}", "Failed to load config.yaml: {0}", "config.yaml 載入失敗: {0}", "config.yamlの読み込み失敗: {0}", "config.yaml 로드 실패: {0}", "config.yaml konnte nicht geladen werden: {0}", "Error al cargar config.yaml: {0}", "Ошибка загрузки config.yaml: {0}", "config.yaml yüklenemedi: {0}", "Gagal memuat config.yaml: {0}", "بارگذاری config.yaml ناموفق: {0}", "فشل تحميل config.yaml: {0}", "config.yaml йөкләү хата: {0}")
    k("Config_ProfilesLoadFailed", "profiles.yaml 加载失败: {0}", "Failed to load profiles.yaml: {0}", "profiles.yaml 載入失敗: {0}", "profiles.yamlの読み込み失敗: {0}", "profiles.yaml 로드 실패: {0}", "profiles.yaml konnte nicht geladen werden: {0}", "Error al cargar profiles.yaml: {0}", "Ошибка загрузки profiles.yaml: {0}", "profiles.yaml yüklenemedi: {0}", "Gagal memuat profiles.yaml: {0}", "بارگذاری profiles.yaml ناموفق: {0}", "فشل تحميل profiles.yaml: {0}", "profiles.yaml йөкләү хата: {0}")

    # ---------- DeepLinkService ----------
    k("DeepLink_RegisterFailed", "协议注册失败: {0}", "Protocol registration failed: {0}", "協定註冊失敗: {0}", "プロトコル登録に失敗: {0}", "프로토콜 등록 실패: {0}", "Protokollregistrierung fehlgeschlagen: {0}", "Error al registrar el protocolo: {0}", "Ошибка регистрации протокола: {0}", "Protokol kaydı başarısız: {0}", "Gagal mendaftarkan protokol: {0}", "ثبت پروتکل ناموفق: {0}", "فشل تسجيل البروتوكول: {0}", "Протокол теркәү хата: {0}")
    k("DeepLink_ImportFailed", "深链导入失败: {0}", "Deep-link import failed: {0}", "深鏈匯入失敗: {0}", "ディープリンクのインポートに失敗: {0}", "딥링크 가져오기 실패: {0}", "Deep-Link-Import fehlgeschlagen: {0}", "Error al importar enlace: {0}", "Ошибка импорта по глубокой ссылке: {0}", "Derin bağlantı içe aktarma başarısız: {0}", "Gagal impor deep-link: {0}", "وارد کردن دیپ‌لینک ناموفق: {0}", "فشل استيراد الرابط العميق: {0}", "Дип-линк кертү хата: {0}")

    # ---------- AutoStartService ----------
    k("AutoStart_DisabledByUser", "开机自启动已被用户禁用，请在任务管理器的「启动应用」中重新启用 Flux Proxy", "Auto launch was disabled by the user; re-enable Flux Proxy in Task Manager's Startup apps", "開機自啟動已被使用者停用，請在工作管理員的「啟動應用」中重新啟用 Flux Proxy", "自動起動はユーザーにより無効化されています。タスクマネージャーで再有効化してください", "자동 실행이 사용자에 의해 비활성화되었습니다. 작업 관리자에서 다시 활성화하세요", "Autostart wurde vom Benutzer deaktiviert; in der Taskverwaltung erneut aktivieren", "El inicio automático fue deshabilitado por el usuario; rehabilítelo en el Administrador de tareas", "Автозапуск отключён пользователем; включите в диспетчере задач", "Otomatik başlatma kullanıcı tarafından devre dışı bırakıldı; Görev Yöneticisi'nden etkinleştirin", "Mulai otomatis dinonaktifkan oleh pengguna; aktifkan kembali di Task Manager", "اجرای خودکار توسط کاربر غیرفعال شده؛ در Task Manager دوباره فعال کنید", "عطّل المستخدم بدء التشغيل التلقائي؛ أعد تمكين Flux Proxy من إدارة المهام", "Автостарт кулланучы тарафыннан сүндерелгән; Task Manager'да кабызыгыз")
    k("AutoStart_DisabledByPolicy", "开机自启动已被系统策略禁用", "Auto launch is disabled by system policy", "開機自啟動已被系統策略停用", "自動起動はポリシーにより無効化", "자동 실행이 시스템 정책으로 비활성화됨", "Autostart durch Richtlinie deaktiviert", "El inicio automático está deshabilitado por directiva", "Автозапуск отключён системной политикой", "Otomatik başlatma sistem ilkesi tarafından devre dışı", "Mulai otomatis dinonaktifkan oleh kebijakan sistem", "اجرای خودکار توسط خط‌مشی سیستم غیرفعال است", "بدء التشغيل التلقائي معطّل بواسطة نهج النظام", "Автостарт системалык сәясәт тарафыннан сүндерелгән")
    k("AutoStart_NotAllowed", "用户未允许开机自启动", "The user did not allow auto launch", "使用者未允許開機自啟動", "ユーザーが自動起動を許可しませんでした", "사용자가 자동 실행을 허용하지 않았습니다", "Der Benutzer hat den Autostart nicht erlaubt", "El usuario no permitió el inicio automático", "Пользователь не разрешил автозапуск", "Kullanıcı otomatik başlatmaya izin vermedi", "Pengguna tidak mengizinkan mulai otomatis", "کاربر اجرای خودکار را تأیید نکرد", "لم يسمح المستخدم ببدء التشغيل التلقائي", "Кулланучы автостартны рөхсәт итмәде")
    k("AutoStart_RunKeyFailed", "无法打开 Run 注册表键", "Could not open the Run registry key", "無法開啟 Run 註冊表鍵", "Run レジストリキーを開けません", "Run 레지스트리 키를 열 수 없습니다", "Run-Registrierungsschlüssel konnte nicht geöffnet werden", "No se pudo abrir la clave del Registro Run", "Не удалось открыть раздел реестра Run", "Run kayıt defteri anahtarı açılamadı", "Tidak bisa membuka kunci registri Run", "کلید رجیستری Run باز نشد", "تعذّر فتح مفتاح التسجيل Run", "Run регистр ачкычы ачылмады")

    # ---------- AppBootstrapper / LightweightManager ----------
    k("Boot_LanguageFailed", "语言设置失败: {0}", "Failed to set language: {0}", "語言設定失敗: {0}", "言語設定に失敗: {0}", "언어 설정 실패: {0}", "Sprache konnte nicht gesetzt werden: {0}", "Error al establecer idioma: {0}", "Ошибка установки языка: {0}", "Dil ayarı başarısız: {0}", "Gagal mengatur bahasa: {0}", "تنظیم زبان ناموفق: {0}", "فشل تعيين اللغة: {0}", "Тел көйләү хата: {0}")
    k("Boot_SkipProxyNoCore", "内核未就绪，已跳过系统代理以避免网络中断", "Core not ready; skipped system proxy to avoid network outage", "核心未就緒，已跳過系統代理以避免網路中斷", "コア未 ready のためプロキシをスキップ", "코어 미준비로 시스템 프록시를 건너뜀", "Kern nicht bereit; Systemproxy übersprungen", "Núcleo no listo; se omitió el proxy del sistema", "Ядро не готово; системный прокси пропущен", "Çekirdek hazır değil; sistem proxy atlandı", "Core belum siap; proxy sistem dilewati", "هسته آماده نیست؛ پروکسی سیستم نادیده گرفته شد", "النواة غير جاهزة؛ تم تخطي بروكسي النظام", "Йөзәк әзер түгел; систем прокси уздырылды")
    k("Boot_HotkeyInitFailed", "热键初始化失败: {0}", "Hotkey init failed: {0}", "熱鍵初始化失敗: {0}", "ホットキー初期化に失敗: {0}", "단축키 초기화 실패: {0}", "Hotkey-Init fehlgeschlagen: {0}", "Error al inicializar atajos: {0}", "Ошибка инициализации горячих клавиш: {0}", "Kısayol başlatma başarısız: {0}", "Gagal menginisialisasi pintasan: {0}", "راه‌اندازی میانبرها ناموفق: {0}", "فشل تهيئة الاختصارات: {0}", "Кыска юлларны башлау хата: {0}")
    k("Boot_HotkeyRegisterFailed", "热键注册失败: {0}", "Hotkey registration failed: {0}", "熱鍵註冊失敗: {0}", "ホットキー登録に失敗: {0}", "단축키 등록 실패: {0}", "Hotkey-Registrierung fehlgeschlagen: {0}", "Error al registrar atajo: {0}", "Ошибка регистрации горячей клавиши: {0}", "Kısayol kaydı başarısız: {0}", "Gagal mendaftarkan pintasan: {0}", "ثبت میانبر ناموفق: {0}", "فشل تسجيل الاختصار: {0}", "Кыска юл теркәү хата: {0}")
    k("Boot_HotkeyExecFailed", "热键执行失败 ({0}): {1}", "Hotkey execution failed ({0}): {1}", "熱鍵執行失敗 ({0}): {1}", "ホットキー実行失敗 ({0}): {1}", "단축키 실행 실패({0}): {1}", "Hotkey-Ausführung fehlgeschlagen ({0}): {1}", "Error al ejecutar atajo ({0}): {1}", "Ошибка выполнения горячей клавиши ({0}): {1}", "Kısayol yürütme başarısız ({0}): {1}", "Gagal menjalankan pintasan ({0}): {1}", "اجرای میانبر ناموفق ({0}): {1}", "فشل تنفيذ الاختصار ({0}): {1}", "Кыска юлны үтәү хата ({0}): {1}")
    k("Boot_HotkeyNotImplemented", "热键动作未实现: {0}", "Hotkey action not implemented: {0}", "熱鍵動作未實現: {0}", "ホットキー動作は未実装: {0}", "단축키 동작 미구현: {0}", "Hotkey-Aktion nicht implementiert: {0}", "Acción de atajo no implementada: {0}", "Действие горячей клавиши не реализовано: {0}", "Kısayol eylemi uygulanmadı: {0}", "Aksi pintasan belum diimplementasi: {0}", "عمل میانبر پیاده‌سازی نشده: {0}", "لم يتم تنفيذ إجراء الاختصار: {0}", "Кыска юл эше тормышка ашырылмаган: {0}")
    k("Boot_TunDisabledNoPrivilege", "当前进程没有管理员权限且服务不可用，已安全关闭 TUN 模式", "No admin rights and service unavailable; TUN safely disabled", "目前程式沒有管理員權限且服務不可用，已安全關閉 TUN 模式", "管理者権限がなくサービスも利用不可のためTUNを安全に無効化", "관리자 권한과 서비스가 없어 TUN을 안전하게 끔", "Keine Admin-Rechte und kein Dienst; TUN sicher deaktiviert", "Sin permisos de admin y servicio no disponible; TUN desactivado", "Нет прав админа и службы; TUN безопасно отключён", "Yönetici hakkı ve servis yok; TUN güvenle kapatıldı", "Tidak ada hak admin dan layanan; TUN dimatikan dengan aman", "دسترسی مدیر و سرویس در دسترس نیست؛ TUN ایمن خاموش شد", "لا صلاحيات مسؤول والخدمة غير متاحة؛ عُطّل TUN بأمان", "Админ хоккы һәм хезмәт юк; TUN имин сүндерелде")
    k("Boot_LightweightAuto", "窗口已关闭 {0} 分钟，自动进入轻量模式", "Window closed for {0} minutes; entering lightweight mode", "視窗已關閉 {0} 分鐘，自動進入輕量模式", "ウィンドウが{0}分閉じていたため軽量モードへ", "창이 {0}분 동안 닫혀 경량 모드로 전환", "Fenster {0} Min. geschlossen; Leichtmodus", "Ventana cerrada {0} minutos; entrando en modo ligero", "Окно закрыто {0} мин; переход в облегчённый режим", "Pencere {0} dakika kapalıydı; hafif moda geçiliyor", "Jendela tertutup {0} menit; masuk mode ringan", "پنجره {0} دقیقه بسته بود؛ ورود به حالت سبک", "أُغلقت النافذة {0} دقيقة؛ الدخول للوضع الخفيف", "Тәрәзә {0} минут ябык иде; Җиңел режимга күчү")
    k("Boot_LightweightAutoFailed", "自动轻量模式失败: {0}", "Auto lightweight failed: {0}", "自動輕量模式失敗: {0}", "自動軽量モードに失敗: {0}", "자동 경량 모드 실패: {0}", "Auto-Leichtmodus fehlgeschlagen: {0}", "Error en modo ligero automático: {0}", "Ошибка авто-облегчённого режима: {0}", "Otomatik hafif mod başarısız: {0}", "Gagal mode ringan otomatis: {0}", "حالت سبک خودکار ناموفق: {0}", "فشل الوضع الخفيف التلقائي: {0}", "Авто-Җиңел режим хата: {0}")
    k("Lightweight_Entered", "已进入轻量模式（主窗口已释放，内核保持运行）", "Entered lightweight mode (main window released; core keeps running)", "已進入輕量模式（主視窗已釋放，核心保持執行）", "軽量モードに移行（メインウィンドウ解放、コアは継続）", "경량 모드 진입(기본 창 해제, 코어 유지)", "Leichtmodus aktiv (Hauptfenster freigegeben; Kern läuft weiter)", "Modo ligero activado (ventana liberada; el núcleo sigue)", "Включён облегчённый режим (окно освобождено, ядро работает)", "Hafif moda geçildi (ana pencere serbest, çekirdek çalışıyor)", "Mode ringan aktif (jendela utama dilepas; core tetap jalan)", "حالت سبک فعال شد (پنجره آزاد شد؛ هسته ادامه دارد)", "دخل الوضع الخفيف (حُررت النافذة؛ النواة تستمر)", "Җиңел режимга керде (тәрәзә азат, йөзәк эшли)")
    k("Lightweight_Exited", "已退出轻量模式", "Exited lightweight mode", "已退出輕量模式", "軽量モードを終了しました", "경량 모드 종료", "Leichtmodus beendet", "Salió del modo ligero", "Вышел из облегчённого режима", "Hafif moddan çıkıldı", "Keluar dari mode ringan", "از حالت سبک خارج شد", "خرج من الوضع الخفيف", "Җиңел режимннан чыкты")
    k("Boot_StartFailed", "启动失败: {0}", "Start failed: {0}", "啟動失敗: {0}", "起動に失敗: {0}", "시작 실패: {0}", "Start fehlgeschlagen: {0}", "Error al iniciar: {0}", "Ошибка запуска: {0}", "Başlatma başarısız: {0}", "Gagal memulai: {0}", "راه‌اندازی ناموفق: {0}", "فشل البدء: {0}", "Башлау хата: {0}")
    k("Boot_CoreStartFailed", "内核启动失败: {0}", "Core start failed: {0}", "核心啟動失敗: {0}", "コア起動に失敗: {0}", "코어 시작 실패: {0}", "Kernstart fehlgeschlagen: {0}", "Error al iniciar el núcleo: {0}", "Ошибка запуска ядра: {0}", "Çekirdek başlatma başarısız: {0}", "Gagal memulai core: {0}", "اجرای هسته ناموفق: {0}", "فشل تشغيل النواة: {0}", "Йөзәк башлау хата: {0}")
    k("Boot_SysProxyApplyFailed", "系统代理应用失败: {0}", "Failed to apply system proxy: {0}", "系統代理應用失敗: {0}", "システムプロキシの適用に失敗: {0}", "시스템 프록시 적용 실패: {0}", "Systemproxy anwenden fehlgeschlagen: {0}", "Error al aplicar proxy del sistema: {0}", "Ошибка применения системного прокси: {0}", "Sistem proxy uygulama başarısız: {0}", "Gagal menerapkan proxy sistem: {0}", "اعمال پروکسی سیستم ناموفق: {0}", "فشل تطبيق بروكسي النظام: {0}", "Систем прокси куллану хата: {0}")
