# -*- coding: utf-8 -*-
"""Provider 对话框/解锁页/连接详情等剩余对话框 i18n 键表。"""


def register(k):
    # ---------- Provider 对话框（规则/代理共用） ----------
    k("Msg_ProviderTitleProxy", "代理 Provider", "Proxy providers", "代理 Provider", "プロキシプロバイダー", "프록시 공급자", "Proxy-Provider", "Proveedores de proxy", "Поставщики прокси", "Proxy sağlayıcılar", "Penyedia proxy", "تأمین‌کنندگان پروکسی", "مزودات البروكسي", "Прокси тәэмин итүчеләр")
    k("Msg_ProviderTitleRules", "规则 Provider", "Rule providers", "規則 Provider", "ルールプロバイダー", "규칙 공급자", "Regel-Provider", "Proveedores de reglas", "Поставщики правил", "Kural sağlayıcılar", "Penyedia aturan", "تأمین‌کنندگان قانون", "مزودات القواعد", "Кагыйдә тәэмин итүчеләр")
    k("Msg_RefreshList", "刷新列表", "Refresh list", "重新整理清單", "一覧を更新", "목록 새로 고침", "Liste aktualisieren", "Actualizar lista", "Обновить список", "Listeyi yenile", "Segarkan daftar", "بازخوانی فهرست", "تحديث القائمة", "Исемлекне яңарту")
    k("Msg_HealthCheck", "健康检查", "Health check", "健康檢查", "ヘルスチェック", "상태 검사", "Health-Check", "Comprobación de estado", "Проверка состояния", "Saglık kontrolü", "Pemeriksaan kesehatan", "بررسی سلامت", "فحص الصحة", "Сәламәтлек тикшерү")
    k("Msg_Loading", "正在加载…", "Loading…", "正在載入…", "読み込み中…", "불러오는 중…", "Wird geladen…", "Cargando…", "Загрузка…", "Yükleniyor…", "Memuat…", "در حال بارگذاری…", "جارٍ التحميل…", "Йөкләнә…")
    k("Msg_NoProxyProviders", "当前订阅没有代理 Provider", "No proxy providers in this profile", "目前訂閱沒有代理 Provider", "プロキシプロバイダーなし", "프록시 공급자 없음", "Keine Proxy-Provider", "Sin proveedores de proxy", "Нет поставщиков прокси", "Proxy sağlayıcı yok", "Tidak ada penyedia proxy", "تأمین‌کننده پروکسی نیست", "لا مزودات بروكسي", "Прокси тәэмин итүче юк")
    k("Msg_NoRuleProviders", "当前订阅没有规则 Provider", "No rule providers in this profile", "目前訂閱沒有規則 Provider", "ルールプロバイダーなし", "규칙 공급자 없음", "Keine Regel-Provider", "Sin proveedores de reglas", "Нет поставщиков правил", "Kural sağlayıcı yok", "Tidak ada penyedia aturan", "تأمین‌کننده قانون نیست", "لا مزودات قواعد", "Кагыйдә тәэмин итүче юк")
    k("Msg_ProviderCount", "共 {0} 个 Provider", "{0} providers", "共 {0} 個 Provider", "{0} 件のプロバイダー", "{0}개 공급자", "{0} Provider", "{0} proveedores", "{0} поставщиков", "{0} sağlayıcı", "{0} penyedia", "{0} تأمین‌کننده", "{0} مزودًا", "{0} тәэмин итүче")
    k("Msg_ProxyNodeCount", "{0} 个节点", "{0} nodes", "{0} 個節點", "{0} ノード", "{0}개 노드", "{0} Knoten", "{0} nodos", "{0} узлов", "{0} düğüm", "{0} node", "{0} گره", "{0} عقدة", "{0} төен")
    k("Msg_RulesMeta", "{0} · {1} · {2} 条", "{0} · {1} · {2} rules", "{0} · {1} · {2} 條", "{0} · {1} · {2}件", "{0} · {1} · {2}개", "{0} · {1} · {2}", "{0} · {1} · {2} reglas", "{0} · {1} · {2} правил", "{0} · {1} · {2} kural", "{0} · {1} · {2} aturan", "{0} · {1} · {2} قانون", "{0} · {1} · {2} قواعد", "{0} · {1} · {2} кагыйдә")
    k("Msg_Update", "更新", "Update", "更新", "更新", "업데이트", "Aktualisieren", "Actualizar", "Обновить", "Güncelle", "Perbarui", "به‌روزرسانی", "تحديث", "Яңарту")
    k("Msg_Updating", "正在更新 {0}…", "Updating {0}…", "正在更新 {0}…", "{0} を更新中…", "{0} 업데이트 중…", "Aktualisiere {0}…", "Actualizando {0}…", "Обновление {0}…", "{0} güncelleniyor…", "Memperbarui {0}…", "در حال به‌روزرسانی {0}…", "جارٍ تحديث {0}…", "Яңартыла {0}…")
    k("Msg_UpdatedOne", "已更新 {0}", "Updated {0}", "已更新 {0}", "{0} を更新しました", "{0} 업데이트됨", "{0} aktualisiert", "{0} actualizado", "{0} обновлено", "{0} güncellendi", "{0} diperbarui", "{0} به‌روزرسانی شد", "تم تحديث {0}", "{0} яңартылды")
    k("Msg_UpdateFailedNamed", "更新失败 {0}: {1}", "Update failed {0}: {1}", "更新失敗 {0}: {1}", "更新失敗 {0}: {1}", "업데이트 실패 {0}: {1}", "Update fehlgeschlagen {0}: {1}", "Error al actualizar {0}: {1}", "Ошибка обновления {0}: {1}", "Güncelleme başarısız {0}: {1}", "Gagal memperbarui {0}: {1}", "به‌روزرسانی ناموفق {0}: {1}", "فشل تحديث {0}: {1}", "Яңарту хата {0}: {1}", )
    k("Msg_UpdatingAll", "正在全部更新…", "Updating all…", "正在全部更新…", "すべて更新中…", "모두 업데이트 중…", "Aktualisiere alle…", "Actualizando todo…", "Обновление всех…", "Tümü güncelleniyor…", "Memperbarui semua…", "در حال به‌روزرسانی همه…", "جارٍ تحديث الكل…", "Барысы яңартыла…")
    k("Msg_UpdateAllDoneCount", "全部更新完成：{0}/{1}", "Update all finished: {0}/{1}", "全部更新完成：{0}/{1}", "すべて更新完了: {0}/{1}", "모두 완료: {0}/{1}", "Fertig: {0}/{1}", "Terminado: {0}/{1}", "Готово: {0}/{1}", "Tamamlandı: {0}/{1}", "Selesai: {0}/{1}", "همه کامل شد: {0}/{1}", "اكتمل: {0}/{1}", "Тәмам: {0}/{1}")
    k("Msg_HealthChecking", "正在健康检查…", "Running health checks…", "正在健康檢查…", "ヘルスチェック中…", "상태 검사 중…", "Health-Check läuft…", "Comprobando estado…", "Проверка состояния…", "Saglık kontrolü yapılıyor…", "Memeriksa kesehatan…", "در حال بررسی سلامت…", "جارٍ فحص الصحة…", "Сәламәтлек тикшерелә…")
    k("Msg_HealthCheckDone", "健康检查完成", "Health check complete", "健康檢查完成", "ヘルスチェック完了", "상태 검사 완료", "Health-Check abgeschlossen", "Comprobación completada", "Проверка завершена", "Saglık kontrolü tamamlandı", "Pemeriksaan selesai", "بررسی سلامت کامل شد", "اكتمل فحص الصحة", "Сәламәтлек тикшерүе тәмам")
    k("Msg_NeverUpdatedShort", "未更新", "Never updated", "未更新", "未更新", "미업데이트", "Nie aktualisiert", "Nunca actualizado", "Не обновлялось", "Hiç güncellenmedi", "Belum diperbarui", "هرگز به‌روزرسانی نشده", "لم يُحدَّث", "Беркай яңартылмады")

    # ---------- 解锁测试状态 ----------
    k("Msg_UnlockUntested", "未测试", "Not tested", "未測試", "未テスト", "미테스트", "Nicht getestet", "Sin probar", "Не тестировалось", "Test edilmedi", "Belum diuji", "تست نشده", "لم يُختبر", "Тикшерелмәгән")
    k("Msg_UnlockTesting", "测试中", "Testing", "測試中", "テスト中", "테스트 중", "Wird getestet", "Probando", "Тестирование", "Test ediliyor", "Sedang diuji", "در حال تست", "جارٍ الاختبار", "Тикшерелә")
    k("Msg_UnlockSupported", "支持", "Supported", "支援", "対応", "지원", "Unterstützt", "Soportado", "Поддерживается", "Destekleniyor", "Didukung", "پشتیبانی می‌شود", "مدعوم", "Тирәкләнә")
    k("Msg_UnlockUnsupported", "不支持", "Unsupported", "不支援", "非対応", "미지원", "Nicht unterstützt", "No soportado", "Не поддерживается", "Desteklenmiyor", "Tidak didukung", "پشتیبانی نمی‌شود", "غير مدعوم", "Тирәкләнми")
    k("Msg_UnlockUnknown", "未知", "Unknown", "未知", "不明", "알 수 없음", "Unbekannt", "Desconocido", "Неизвестно", "Bilinmiyor", "Tidak diketahui", "نامشخص", "غير معروف", "Билгесез")
    k("Msg_UnlockFailed", "失败", "Failed", "失敗", "失敗", "실패", "Fehlgeschlagen", "Falló", "Ошибка", "Başarısız", "Gagal", "ناموفق", "فشل", "Хата")

    # ---------- 首页错误 ----------
    k("Msg_SysProxyToggleFailedTitle", "系统代理切换失败", "System proxy toggle failed", "系統代理切換失敗", "システムプロキシ切替に失敗", "시스템 프록시 전환 실패", "Systemproxy-Wechsel fehlgeschlagen", "Error al alternar proxy del sistema", "Ошибка переключения системного прокси", "Sistem proxy geçişi başarısız", "Gagal mengalihkan proxy sistem", "تغییر پروکسی سیستم ناموفق بود", "فشل تبديل بروكسي النظام", "Систем прокси алмаштыру хата")
    k("Msg_TunToggleFailedTitle", "TUN 切换失败", "TUN toggle failed", "TUN 切換失敗", "TUN切替に失敗", "TUN 전환 실패", "TUN-Wechsel fehlgeschlagen", "Error al alternar TUN", "Ошибка переключения TUN", "TUN geçişi başarısız", "Gagal mengalihkan TUN", "تغییر TUN ناموفق بود", "فشل تبديل TUN", "TUN алмаштыру хата")
    k("Msg_CoreRestartFailedTitle", "内核重启失败", "Core restart failed", "核心重啟失敗", "コア再起動に失敗", "코어 재시작 실패", "Kern-Neustart fehlgeschlagen", "Error al reiniciar el núcleo", "Ошибка перезапуска ядра", "Çekirdek yeniden başlatma başarısız", "Gagal merestart core", "ری‌استارت هسته ناموفق بود", "فشل إعادة تشغيل النواة", "Йөзәкне яңадан башлау хата")

    # ---------- 连接详情 ----------
    k("Msg_CloseThisConn", "关闭此连接", "Close this connection", "關閉此連接", "この接続を閉じる", "이 연결 닫기", "Diese Verbindung schließen", "Cerrar esta conexión", "Закрыть это соединение", "Bu bağlantıyı kapat", "Tutup koneksi ini", "بستن این اتصال", "أغلق هذا الاتصال", "Бу тоташуны ябу")
    k("Msg_Back", "返回", "Back", "返回", "戻る", "뒤로", "Zurück", "Volver", "Назад", "Geri", "Kembali", "بازگشت", "رجوع", "Кайту")
    k("Msg_DetailNetwork", "网络: {0} ({1})", "Network: {0} ({1})", "網路: {0} ({1})", "ネットワーク: {0} ({1})", "네트워크: {0} ({1})", "Netzwerk: {0} ({1})", "Red: {0} ({1})", "Сеть: {0} ({1})", "Ağ: {0} ({1})", "Jaringan: {0} ({1})", "شبکه: {0} ({1})", "الشبكة: {0} ({1})", "Челтәр: {0} ({1})")
    k("Msg_DetailHost", "主机: {0}", "Host: {0}", "主機: {0}", "ホスト: {0}", "호스트: {0}", "Host: {0}", "Host: {0}", "Хост: {0}", "Ana makine: {0}", "Host: {0}", "میزبان: {0}", "المضيف: {0}", "Хост: {0}")
    k("Msg_DetailDestination", "目标: {0}", "Destination: {0}", "目標: {0}", "宛先: {0}", "대상: {0}", "Ziel: {0}", "Destino: {0}", "Цель: {0}", "Hedef: {0}", "Tujuan: {0}", "مقصد: {0}", "الوجهة: {0}", "Максат: {0}")
    k("Msg_DetailSource", "来源: {0}", "Source: {0}", "來源: {0}", "送信元: {0}", "출처: {0}", "Quelle: {0}", "Origen: {0}", "Источник: {0}", "Kaynak: {0}", "Sumber: {0}", "منبع: {0}", "المصدر: {0}", "Чыганак: {0}")
    k("Msg_DetailRule", "规则: {0}", "Rule: {0}", "規則: {0}", "ルール: {0}", "규칙: {0}", "Regel: {0}", "Regla: {0}", "Правило: {0}", "Kural: {0}", "Aturan: {0}", "قانون: {0}", "القاعدة: {0}", "Кагыйдә: {0}")
    k("Msg_DetailChains", "链路: {0}", "Chains: {0}", "鏈路: {0}", "チェーン: {0}", "체인: {0}", "Kette: {0}", "Cadena: {0}", "Цепочка: {0}", "Zincir: {0}", "Rantai: {0}", "زنجیره: {0}", "السلسلة: {0}", "Чылбыр: {0}")
    k("Msg_DetailProcess", "进程: {0}", "Process: {0}", "進程: {0}", "プロセス: {0}", "프로세스: {0}", "Prozess: {0}", "Proceso: {0}", "Процесс: {0}", "Süreç: {0}", "Proses: {0}", "فرایند: {0}", "العملية: {0}", "Процесс: {0}")
    k("Msg_DetailTraffic", "下载: {0}   上传: {1}", "Down: {0}   Up: {1}", "下載: {0}   上傳: {1}", "DL: {0}   UL: {1}", "다운: {0}   업: {1}", "Runter: {0}   Hoch: {1}", "Bajada: {0}   Subida: {1}", "Загрузка: {0}   Отдача: {1}", "İndirme: {0}   Yükleme: {1}", "Unduh: {0}   Unggah: {1}", "دانلود: {0}   آپلود: {1}", "تنزيل: {0}   رفع: {1}", "Йөкләү: {0}   Тоташу: {1}")
    k("Msg_DetailTime", "时间: {0}", "Time: {0}", "時間: {0}", "時刻: {0}", "시간: {0}", "Zeit: {0}", "Hora: {0}", "Время: {0}", "Zaman: {0}", "Waktu: {0}", "زمان: {0}", "الوقت: {0}", "Вакыт: {0}")
def register_extra(k):
    k("Msg_QrTitle", "二维码：{0}", "QR code: {0}", "二維碼：{0}", "QRコード: {0}", "QR 코드: {0}", "QR-Code: {0}", "Código QR: {0}", "QR-код: {0}", "QR kod: {0}", "Kode QR: {0}", "کد QR: {0}", "رمز QR: {0}", "QR код: {0}")
    k("Msg_QrFailed", "二维码生成失败: {0}", "QR generation failed: {0}", "二維碼產生失敗: {0}", "QR生成に失敗: {0}", "QR 생성 실패: {0}", "QR-Generierung fehlgeschlagen: {0}", "Error al generar QR: {0}", "Ошибка генерации QR: {0}", "QR üretimi başarısız: {0}", "Gagal membuat QR: {0}", "ایجاد QR ناموفق: {0}", "فشل إنشاء رمز QR: {0}", "QR ясау хата: {0}")
    k("Msg_LoopbackTitle", "UWP Loopback 工具", "UWP Loopback tool", "UWP Loopback 工具", "UWP Loopbackツール", "UWP Loopback 도구", "UWP-Loopback-Tool", "Herramienta UWP Loopback", "Инструмент UWP Loopback", "UWP Loopback aracı", "Alat UWP Loopback", "ابزار UWP Loopback", "أداة UWP Loopback", "UWP Loopback коралы")
    k("Msg_LoopbackHint", "勾选需要允许本地回环联网的 UWP 应用，应用更改时会请求管理员授权。", "Check UWP apps that should be allowed loopback; applying requests admin consent.", "勾選需要允許本地回環連網的 UWP 應用，應用變更時會請求管理員授權。", "ループバックを許可するUWPアプリを選択（適用時に管理者権限）", "루프백을 허용할 UWP 앱 선택(적용 시 관리자 권한)", "UWP-Apps wählen, die Loopback dürfen (Admin nötig)", "Marque las apps UWP que permitan loopback; se pedirán permisos de admin", "Отметьте UWP-приложения для loopback (нужны права админа)", "Loopback'e izin verilecek UWP uygulamalarını seçin (yönetici gerekir)", "Centang aplikasi UWP yang diizinkan loopback; butuh izin admin", "برنامه‌های UWP مجاز را انتخاب کنید (نیاز به دسترسی مدیر)", "حدد تطبيقات UWP المسموح لها بالاتصال المحلي؛ يتطلب صلاحيات المسؤول", "Loopback рөхсәт ителгән UWP кушакларын сайлагыз (админ кирәк)")
    k("Msg_LoopbackApply", "应用更改", "Apply changes", "應用變更", "変更を適用", "변경 적용", "Änderungen anwenden", "Aplicar cambios", "Применить изменения", "Değişiklikleri uygula", "Terapkan perubahan", "اعمال تغییرات", "تطبيق التغييرات", "Үзгәрешләрне куллану")
    k("Msg_LoopbackApplying", "正在应用…", "Applying…", "正在應用…", "適用中…", "적용 중…", "Wird angewendet…", "Aplicando…", "Применение…", "Uygulanıyor…", "Menerapkan…", "در حال اعمال…", "جارٍ التطبيق…", "Кулланыла…")
    k("Msg_LoopbackApplied", "已应用 Loopback 更改。", "Loopback changes applied.", "已應用 Loopback 變更。", "Loopbackの変更を適用しました", "Loopback 변경이 적용되었습니다", "Loopback-Änderungen angewendet", "Cambios de loopback aplicados", "Изменения loopback применены", "Loopback değişiklikleri uygulandı", "Perubahan loopback diterapkan", "تغییرات Loopback اعمال شد", "تم تطبيق تغييرات Loopback", "Loopback үзгәрешләре кулланды")
    k("Msg_LoopbackFailed", "应用失败: {0}", "Apply failed: {0}", "應用失敗: {0}", "適用に失敗: {0}", "적용 실패: {0}", "Anwenden fehlgeschlagen: {0}", "Error al aplicar: {0}", "Ошибка применения: {0}", "Uygulama başarısız: {0}", "Gagal menerapkan: {0}", "اعمال ناموفق: {0}", "فشل التطبيق: {0}", "Куллану хата: {0}")
    k("Msg_LoopbackLoadFailed", "读取 UWP 应用列表失败: {0}", "Failed to list UWP apps: {0}", "讀取 UWP 應用清單失敗: {0}", "UWPアプリ一覧の取得に失敗: {0}", "UWP 앱 목록 읽기 실패: {0}", "UWP-Liste fehlgeschlagen: {0}", "Error al listar apps UWP: {0}", "Ошибка списка UWP-приложений: {0}", "UWP uygulama listesi alınamadı: {0}", "Gagal membaca daftar aplikasi UWP: {0}", "خواندن فهرست برنامه‌های UWP ناموفق: {0}", "فشل قراءة قائمة تطبيقات UWP: {0}", "UWP исемлеген уку хата: {0}")
    k("Msg_ColumnSettings", "列设置", "Column settings", "欄位設定", "列の設定", "열 설정", "Spalten-Einstellungen", "Ajustes de columnas", "Настройки столбцов", "Sütun ayarları", "Pengaturan kolom", "تنظیمات ستون‌ها", "إعدادات الأعمدة", "Багана көйләүләре")
    k("Msg_LayoutTable", "表格", "Table", "表格", "テーブル", "테이블", "Tabelle", "Tabla", "Таблица", "Tablo", "Tabel", "جدول", "جدول", "Таблица")
    k("Msg_LayoutList", "列表", "List", "清單", "リスト", "목록", "Liste", "Lista", "Список", "Liste", "Daftar", "فهرست", "قائمة", "Исемлек")
    k("Msg_NoVisibleColumns", "至少保留一列可见。", "At least one column must stay visible.", "至少保留一欄可見。", "少なくとも1列は表示してください", "최소 한 개 열은 표시해야 합니다", "Mindestens eine Spalte sichtbar lassen", "Deja al menos una columna visible", "Минимум один столбец должен быть видим", "En az bir sütun görünür kalmalı", "Sedikitnya satu kolom harus terlihat", "حداقل یک ستون باید نمایان باشد", "يجب أن يبقى عمود واحد ظاهرًا على الأقل", "Кимдә бер багана күренмәле")
    k("Msg_UacCancelled", "用户取消了 UAC 授权", "UAC consent cancelled", "使用者取消了 UAC 授權", "UACをキャンセルしました", "UAC 권한이 취소되었습니다", "UAC abgebrochen", "Consentimiento UAC cancelado", "Пользователь отменил UAC", "Kullanıcı UAC'ı iptal etti", "Persetujuan UAC dibatalkan", "کاربر UAC را لغو کرد", "ألغى المستخدم موافقة UAC", "Кулланучы UAC'ны баш тартты")
    k("Settings_OpenLoopback", "打开工具", "Open tool", "開啟工具", "ツールを開く", "도구 열기", "Tool öffnen", "Abrir herramienta", "Открыть инструмент", "Aracı aç", "Buka alat", "باز کردن ابزار", "افتح الأداة", "Коралны ачу")
    k("Profiles_MenuQr", "二维码", "QR code", "二維碼", "QRコード", "QR 코드", "QR-Code", "Código QR", "QR-код", "QR kod", "Kode QR", "کد QR", "رمز QR", "QR код")
    k("Msg_QrRemoteOnly", "仅远程订阅支持二维码（本地配置没有 URL）", "Only remote profiles have a QR code (local profiles have no URL)", "僅遠端訂閱支援二維碼（本地設定沒有 URL）", "QRコードはリモート購読のみ対応", "QR 코드는 원격 구독만 지원", "QR nur für Remote-Profile", "El QR solo está disponible para perfiles remotos", "QR-код только для удалённых подписок", "QR yalnızca uzak profiller için", "QR hanya untuk profil jarak jauh", "کد QR فقط برای پروفایل‌های راه‌دور", "رمز QR متاح للملفات البعيدة فقط", "QR код тик remote профильләр өчен")
